// AUTO-GENERATED by devtools/generators/emit_loader_pins.py -- do not edit.
// Source: data/targets/*.json (pinned target manifests).
// Regenerate with `make loader-pins-header`.
//
// One immutable row per supported GTA V build the loader can auto-detect.
// A row exists only for a manifest whose per-build addresses were derived
// from that build's decrypted eboot (loader.status != pending); the loader
// probes each row's version signature at inject time and runs with the
// first matching build. Unsupported/undumped builds match no row and are
// rejected cleanly (notification, game untouched).
#pragma once

#include "gtavmenu/build_pin.h"

#define GTAV_BUILD_PIN_COUNT 1u

static const GtavBuildPin gtav_build_pins[] = {
  {
    "PPSA04264_01.010.002_DISC",
    (uintptr_t)0x1a51840ull,
    {0x8b, 0x05, 0x4a, 0xc1, 0xb1, 0x02, 0x48, 0x8b, 0x0f, 0x89, 0x01, 0xc3, 0xcc, 0xcc, 0xcc, 0xcc},
    (uintptr_t)0x1bc8ed0ull,
    (uintptr_t)0x1bc8ee0ull,
    14u,
    16u,
    {0x55, 0x48, 0x89, 0xe5, 0x53, 0x50, 0x48, 0x8b, 0x05, 0xab, 0x0b, 0xec, 0x03, 0x48, 0x89, 0xfb},
    (uintptr_t)0x3ff000ull,
    (uintptr_t)0x3798000ull,
    (uintptr_t)0x5a89a88ull,
    (uintptr_t)0x8ull,
  },
};
