// AUTO-GENERATED by devtools/generators/generate_object_registry.py
// Source: data/objects/gtav-object-names.txt
// Do not edit by hand. Regenerate with `make object-registry`.
//
// Object category display names, in catalog category-index order. native_bridge.cpp
// prepends "All" (index 0); a catalog entry with category index N maps here to N.
// 10 categories.

    "Containers",
    "Barrels",
    "Roadwork",
    "Ramps",
    "Nature",
    "Sports",
    "Hazards",
    "Street",
    "Furniture",
    "Fun",
