// AUTO-GENERATED by devtools/generators/generate_object_registry.py
// Source: data/objects/gtav-object-names.txt
// Do not edit by hand. Regenerate with `make object-registry`.
//
// Initializer list for gtav_object_catalog[] (see feature_catalog.c).
// Columns: {label, model, category index, joaat(model)}.
// 90 entries across 10 categories.

  {"Wood Box S", "prop_box_wood01a", 0, 0x45709ef7u},  // Containers
  {"Wood Box M", "prop_box_wood02a", 0, 0x17a0c6d0u},  // Containers
  {"Crate", "prop_box_wood02a_pu", 0, 0x9109dfbcu},  // Containers
  {"Wood Box L", "prop_box_wood03a", 0, 0x876cbcd2u},  // Containers
  {"Wood Box XL", "prop_box_wood04a", 0, 0xb131133au},  // Containers
  {"Crate Small", "prop_crate_01a", 0, 0x43d4d056u},  // Containers
  {"Crate Large", "prop_crate_02a", 0, 0x78df72d2u},  // Containers
  {"Box Pile", "prop_boxpile_07d", 0, 0x1efd2c41u},  // Containers
  {"Cardboard Box", "prop_cs_cardbox_01", 0, 0x4da19524u},  // Containers
  {"Pallet", "prop_pallet_02a", 0, 0x317b39edu},  // Containers
  {"Tool Box", "prop_tool_box_01", 0, 0x34e9239fu},  // Containers
  {"Tool Box 2", "prop_tool_box_04", 0, 0x8a68ce9du},  // Containers
  {"Tool Chest", "prop_toolchest_01", 0, 0x9c33fc5cu},  // Containers
  {"Tool Chest 2", "prop_toolchest_04", 0, 0xcc5ddc8fu},  // Containers
  {"Skip", "prop_skip_01a", 0, 0xe8e8aadau},  // Containers
  {"Dumpster", "prop_dumpster_01a", 0, 0x0cffb6b0u},  // Containers
  {"Barrel", "prop_barrel_01a", 1, 0x9866a5dbu},  // Barrels
  {"Oil Drum", "prop_barrel_02a", 1, 0x4d6410f7u},  // Barrels
  {"Barrel Rusty", "prop_barrel_03a", 1, 0x055c8249u},  // Barrels
  {"Barrel Pile", "prop_barrel_pile_01", 1, 0x6277ec7eu},  // Barrels
  {"Barrel Pile 2", "prop_barrel_pile_02", 1, 0xf07d888bu},  // Barrels
  {"Gas Tank", "prop_gas_tank_01a", 1, 0x81120072u},  // Barrels
  {"Jerry Can", "prop_jerrycan_01a", 1, 0x2edd9003u},  // Barrels
  {"Cone Tall", "prop_roadcone01a", 2, 0xe0264f5du},  // Roadwork
  {"Traffic Cone", "prop_roadcone02a", 2, 0xc2339364u},  // Roadwork
  {"MP Cone", "prop_mp_cone_01", 2, 0x37fdc243u},  // Roadwork
  {"MP Cone 2", "prop_mp_cone_02", 2, 0x4a4266ccu},  // Roadwork
  {"Barrier Fence", "prop_barrier_work01a", 2, 0x3feed2e2u},  // Roadwork
  {"Barrier Mesh", "prop_barrier_work02a", 2, 0x89b5e793u},  // Roadwork
  {"Barrier Solid", "prop_barrier_work04a", 2, 0xde469bcfu},  // Roadwork
  {"Barrier", "prop_barrier_work05", 2, 0xf7752d66u},  // Roadwork
  {"Barrier Plastic", "prop_barrier_work06a", 2, 0x2da13cc7u},  // Roadwork
  {"Water Barrier", "prop_barrier_wat_01a", 2, 0xcdd8fe00u},  // Roadwork
  {"Water Barrier 2", "prop_barrier_wat_03a", 2, 0x7c035ca2u},  // Roadwork
  {"MP Barrier", "prop_mp_barrier_01", 2, 0x33bee4beu},  // Roadwork
  {"Sign Board", "prop_consign_01a", 2, 0x6e329a95u},  // Roadwork
  {"Work Light", "prop_worklight_01a", 2, 0x08b103b5u},  // Roadwork
  {"Work Light 2", "prop_worklight_03a", 2, 0xeb174aeeu},  // Roadwork
  {"Generator", "prop_generator_03b", 2, 0xfc96f411u},  // Roadwork
  {"Ramp Small", "prop_mp_ramp_01", 3, 0xb157c9e4u},  // Ramps
  {"Ramp Medium", "prop_mp_ramp_02", 3, 0xf4f1511eu},  // Ramps
  {"Ramp Large", "prop_mp_ramp_03", 3, 0x93948e5eu},  // Ramps
  {"Birch Tree", "prop_tree_birch_01", 4, 0xc7867088u},  // Nature
  {"Cedar Tree", "prop_tree_cedar_02", 4, 0x81fa6043u},  // Nature
  {"Cedar Tree 2", "prop_tree_cedar_03", 4, 0x74bfc5ceu},  // Nature
  {"Pine Tree", "prop_tree_pine_01", 4, 0xa0542754u},  // Nature
  {"Pine Tree 2", "prop_tree_pine_02", 4, 0x52498b38u},  // Nature
  {"Palm Tree", "prop_palm_med_01a", 4, 0x8ea2348cu},  // Nature
  {"Palm Small", "prop_palm_sm_01e", 4, 0x79db7af1u},  // Nature
  {"Bush", "prop_bush_med_01", 4, 0xfe6e928au},  // Nature
  {"Bush 2", "prop_bush_med_02", 4, 0x0e1d31e7u},  // Nature
  {"Bush 3", "prop_bush_med_03", 4, 0x98b1c712u},  // Nature
  {"Beach Ball", "prop_beach_volball01", 5, 0xc79a987eu},  // Sports
  {"Basketball Net", "prop_basketball_net", 5, 0x274ba905u},  // Sports
  {"Bowling Ball", "prop_bowling_ball", 5, 0xde6c3ffeu},  // Sports
  {"Pool Ball", "prop_pool_ball_01", 5, 0x1c407029u},  // Sports
  {"Tennis Ball", "prop_tennis_ball", 5, 0x996e76adu},  // Sports
  {"Golf Ball", "prop_golf_ball", 5, 0xaf0e3f9fu},  // Sports
  {"Golf Club", "prop_golf_iron_01", 5, 0x13edbd11u},  // Sports
  {"Explosive Barrel", "prop_barrel_exp_01a", 6, 0xafdd8cbbu},  // Hazards
  {"Spike Strip", "prop_tyre_spike_01", 6, 0xfc8fc916u},  // Hazards
  {"Fire Hydrant", "prop_fire_hydrant_1", 6, 0x0bf8ad31u},  // Hazards
  {"Fire Hydrant 2", "prop_fire_hydrant_2", 6, 0xfa2e099cu},  // Hazards
  {"Traffic Light", "prop_traffic_01a", 7, 0x3e2b73a4u},  // Street
  {"Street Light", "prop_streetlight_01", 7, 0xc09cb0b8u},  // Street
  {"Street Light 2", "prop_streetlight_03b", 7, 0x4f193d24u},  // Street
  {"Post Box", "prop_postbox_01a", 7, 0x51400793u},  // Street
  {"Trash Bin", "prop_bin_01a", 7, 0x55aea3b1u},  // Street
  {"Trash Bin 2", "prop_bin_07a", 7, 0xf25fe3fdu},  // Street
  {"Trash Bin Open", "prop_bin_08open", 7, 0xe75f1884u},  // Street
  {"ATM", "prop_atm_01", 7, 0xcc179926u},  // Street
  {"Soda Machine", "prop_vend_soda_01", 7, 0x3b21c5e7u},  // Street
  {"Portaloo", "prop_portaloo_01a", 7, 0x28a7a0b9u},  // Street
  {"Trolley", "prop_cs_trolley_01", 7, 0x961ccc04u},  // Street
  {"Bench", "prop_bench_01a", 8, 0x6ba514acu},  // Furniture
  {"Chair", "prop_chair_01a", 8, 0x1f550c17u},  // Furniture
  {"Office Chair", "prop_cs_office_chair", 8, 0xbd564507u},  // Furniture
  {"Money Bag", "prop_money_bag_01", 9, 0x113fd533u},  // Fun
  {"Cash Pile", "prop_cash_pile_01", 9, 0xee5ebc97u},  // Fun
  {"Cash Crate", "prop_cash_crate_01", 9, 0xe44d5cecu},  // Fun
  {"Cash Case", "prop_cash_case_01", 9, 0x5f9a1284u},  // Fun
  {"Gold Bar", "prop_gold_bar", 9, 0xf046ea37u},  // Fun
  {"Health Pack", "prop_ld_health_pack", 9, 0x28781518u},  // Fun
  {"Backpack", "prop_michael_backpack", 9, 0x5e7d2624u},  // Fun
  {"Protest Sign", "prop_cs_protest_sign_01", 9, 0xb856d4ceu},  // Fun
  {"Tequila Bottle", "prop_tequila_bottle", 9, 0xdf22d168u},  // Fun
  {"Burger", "prop_cs_burger_01", 9, 0x858bb1d0u},  // Fun
  {"Drug Package", "prop_drug_package_02", 9, 0x8ae084d2u},  // Fun
  {"Weed Block", "prop_weed_block_01", 9, 0xffe63dc1u},  // Fun
  {"Parachute", "p_parachute_s", 9, 0x4bb13d0du},  // Fun
