// AUTO-GENERATED by devtools/generators/generate_ped_registry.py
// Source: data/peds/gtav-ped-names.txt
// Do not edit by hand. Regenerate with `make ped-registry`.
//
// Ped category display names, in catalog category-index order. native_bridge.cpp
// prepends "All" (index 0); a catalog entry with category index N maps here to N.
// 14 categories.

    "Player",
    "Animal",
    "Ambient Female",
    "Ambient Male",
    "Cutscene",
    "Gang Female",
    "Gang Male",
    "Story",
    "Multiplayer",
    "Scenario Female",
    "Scenario Male",
    "Story Scenario Female",
    "Story Scenario Male",
    "Others",
