// AUTO-GENERATED by devtools/generators/generate_ped_registry.py
// Source: data/peds/gtav-ped-names.txt
// Validation: none (candidate superset)
// Do not edit by hand. Regenerate with `make ped-registry`.
//
// Initializer list for gtav_ped_model_catalog[] (see feature_catalog.c).
// Columns: {caption, model, category index, joaat(model)}.
// 1104 entries.

  {"Franklin", "player_one", 0, 0x9b22dbafu},  // Player
  {"Franklin Aged", "p_franklin_02", 0, 0xaf10bd56u},  // Player
  {"Freemode MP Female", "mp_f_freemode_01", 0, 0x9c9effd8u},  // Player
  {"Freemode MP Male", "mp_m_freemode_01", 0, 0x705e61f2u},  // Player
  {"Michael", "player_zero", 0, 0x0d7114c9u},  // Player
  {"Michael Aged", "p_michael_02", 0, 0xd2ee1337u},  // Player
  {"Trevor", "player_two", 0, 0x9b810fa2u},  // Player
  {"Australian Shepherd", "a_c_shepherd", 1, 0x431fc24cu},  // Animal
  {"Boar", "a_c_boar", 1, 0xce5ff074u},  // Animal
  {"Boar 2 (Halloween)", "a_c_boar_02", 1, 0x8b297ef4u},  // Animal
  {"Cat", "a_c_cat_01", 1, 0x573201b8u},  // Animal
  {"Cat 2", "a_c_cat_02", 1, 0x6a50a7f5u},  // Animal
  {"Chimp", "a_c_chimp_02", 1, 0x7e0c64aau},  // Animal
  {"Chimp 2", "a_c_chimp", 1, 0xa8683715u},  // Animal
  {"Chop (Old)", "a_c_chop_02", 1, 0x3df40fc1u},  // Animal
  {"Chop (Young)", "a_c_chop", 1, 0x14ec17eau},  // Animal
  {"Cormorant", "a_c_cormorant", 1, 0x56e29962u},  // Animal
  {"Cow", "a_c_cow", 1, 0xfcfa9e1eu},  // Animal
  {"Coyote", "a_c_coyote", 1, 0x644ac75eu},  // Animal
  {"Coyote (Halloween)", "a_c_coyote_02", 1, 0x2bc8d6c7u},  // Animal
  {"Crow", "a_c_crow", 1, 0x18012a9fu},  // Animal
  {"Deer", "a_c_deer", 1, 0xd86b5a95u},  // Animal
  {"Deer (Halloween)", "a_c_deer_02", 1, 0xaa4b67d0u},  // Animal
  {"Dolphin", "a_c_dolphin", 1, 0x8bbab455u},  // Animal
  {"Fish", "a_c_fish", 1, 0x2fd800b7u},  // Animal
  {"Hammerhead Shark", "a_c_sharkhammer", 1, 0x3c831724u},  // Animal
  {"Hawk", "a_c_chickenhawk", 1, 0xaab71f62u},  // Animal
  {"Hen", "a_c_hen", 1, 0x6af51fafu},  // Animal
  {"Humpback Whale", "a_c_humpback", 1, 0x471be4b2u},  // Animal
  {"Husky", "a_c_husky", 1, 0x4e8f95a2u},  // Animal
  {"Killer Whale", "a_c_killerwhale", 1, 0x8d8ac8b9u},  // Animal
  {"Mountain Lion", "a_c_mtlion", 1, 0x1250d7bau},  // Animal
  {"Mountain Lion (Halloween)", "a_c_mtlion_02", 1, 0x8d2b8f51u},  // Animal
  {"Panther", "a_c_panther", 1, 0xe71d5e68u},  // Animal
  {"Pig", "a_c_pig", 1, 0xb11bab56u},  // Animal
  {"Pigeon", "a_c_pigeon", 1, 0x06a20728u},  // Animal
  {"Poodle", "a_c_poodle", 1, 0x431d501cu},  // Animal
  {"Pug", "a_c_pug", 1, 0x6d362854u},  // Animal
  {"Pug (Halloween)", "a_c_pug_02", 1, 0x3ff2ba91u},  // Animal
  {"Rabbit", "a_c_rabbit_01", 1, 0xdfb55c81u},  // Animal
  {"Rabbit (Huge)", "a_c_rabbit_02", 1, 0x5c9d564bu},  // Animal
  {"Rat", "a_c_rat", 1, 0xc3b52966u},  // Animal
  {"Retriever", "a_c_retriever", 1, 0x349f33e1u},  // Animal
  {"Rhesus The Chimp", "a_c_rhesus", 1, 0xc2d06f53u},  // Animal
  {"Rottweiler", "a_c_rottweiler", 1, 0x9563221du},  // Animal
  {"Rottweiler 2", "a_c_rottweiler_02", 1, 0xab755761u},  // Animal
  {"Seagull", "a_c_seagull", 1, 0xd3939dfdu},  // Animal
  {"Stingray", "a_c_stingray", 1, 0xa148614du},  // Animal
  {"Tiger Shark", "a_c_sharktiger", 1, 0x06c3f072u},  // Animal
  {"Westie", "a_c_westy", 1, 0xad7844bbu},  // Animal
  {"Beach Female", "a_f_m_beach_01", 2, 0x303638a7u},  // Ambient Female
  {"Beach Tramp Female", "a_f_m_trampbeac_01", 2, 0x8ca0c266u},  // Ambient Female
  {"Beach Young Female", "a_f_y_beach_01", 2, 0xc79f6928u},  // Ambient Female
  {"Beach Young Female 2", "a_f_y_beach_02", 2, 0xb920cc2bu},  // Ambient Female
  {"Beverly Hills Female", "a_f_m_bevhills_01", 2, 0xbe086efdu},  // Ambient Female
  {"Beverly Hills Female 2", "a_f_m_bevhills_02", 2, 0xa039335fu},  // Ambient Female
  {"Beverly Hills Young Female", "a_f_y_bevhills_01", 2, 0x445ac854u},  // Ambient Female
  {"Beverly Hills Young Female 2", "a_f_y_bevhills_02", 2, 0x5c2cf7f8u},  // Ambient Female
  {"Beverly Hills Young Female 3", "a_f_y_bevhills_03", 2, 0x20c8012fu},  // Ambient Female
  {"Beverly Hills Young Female 4", "a_f_y_bevhills_04", 2, 0x36df2d5du},  // Ambient Female
  {"Beverly Hills Young Female 5", "a_f_y_bevhills_05", 2, 0x92e7e56du},  // Ambient Female
  {"Bodybuilder Female", "a_f_m_bodybuild_01", 2, 0x3bd99114u},  // Ambient Female
  {"Business Female 2", "a_f_m_business_02", 2, 0x1fc37dbcu},  // Ambient Female
  {"Business Young Female", "a_f_y_business_01", 2, 0x2799efd8u},  // Ambient Female
  {"Business Young Female 2", "a_f_y_business_02", 2, 0x31430342u},  // Ambient Female
  {"Business Young Female 3", "a_f_y_business_03", 2, 0xae86fdb4u},  // Ambient Female
  {"Business Young Female 4", "a_f_y_business_04", 2, 0xb7c61032u},  // Ambient Female
  {"Car Club Female 1", "a_f_y_carclub_01", 2, 0xfd08c54bu},  // Ambient Female
  {"Car Club Female 2", "a_f_y_carclub_02", 2, 0x0e3b67b0u},  // Ambient Female
  {"Casual Casino Guest", "a_f_y_gencaspat_01", 2, 0x911b94b2u},  // Ambient Female
  {"Club Customer Female 1", "a_f_y_clubcust_01", 2, 0x67f6dbcdu},  // Ambient Female
  {"Club Customer Female 2", "a_f_y_clubcust_02", 2, 0x154e3679u},  // Ambient Female
  {"Club Customer Female 3", "a_f_y_clubcust_03", 2, 0x00a40d25u},  // Ambient Female
  {"Club Customer Female 4", "a_f_y_clubcust_04", 2, 0x2ee1e9a0u},  // Ambient Female
  {"Downtown Female", "a_f_m_downtown_01", 2, 0x654ad86eu},  // Ambient Female
  {"Dressy Female", "a_f_y_scdressy_01", 2, 0xdb5ec400u},  // Ambient Female
  {"East SA Female", "a_f_m_eastsa_01", 2, 0x9d3dcb7au},  // Ambient Female
  {"East SA Female 2", "a_f_m_eastsa_02", 2, 0x63c8d891u},  // Ambient Female
  {"East SA Young Female", "a_f_y_eastsa_01", 2, 0xf5b0079du},  // Ambient Female
  {"East SA Young Female 2", "a_f_y_eastsa_02", 2, 0x0438a4aeu},  // Ambient Female
  {"East SA Young Female 3", "a_f_y_eastsa_03", 2, 0x51c03fa4u},  // Ambient Female
  {"Epsilon Female", "a_f_y_epsilon_01", 2, 0x689c2a80u},  // Ambient Female
  {"Fat Black Female", "a_f_m_fatbla_01", 2, 0xfab48bcbu},  // Ambient Female
  {"Fat Cult Female", "a_f_m_fatcult_01", 2, 0xb5cf80e4u},  // Ambient Female
  {"Fat White Female", "a_f_m_fatwhite_01", 2, 0x38bad33bu},  // Ambient Female
  {"Female Agent", "a_f_y_femaleagent", 2, 0x50610c43u},  // Ambient Female
  {"Fitness Female", "a_f_y_fitness_01", 2, 0x457c64fbu},  // Ambient Female
  {"Fitness Female 2", "a_f_y_fitness_02", 2, 0x13c4818cu},  // Ambient Female
  {"Formal Casino Guest", "a_f_y_smartcaspat_01", 2, 0x10a4aed2u},  // Ambient Female
  {"General Biker Female", "a_f_m_genbiker_01", 2, 0x749b5065u},  // Ambient Female
  {"General Hot Young Female", "a_f_y_genhot_01", 2, 0x2f4aec3eu},  // Ambient Female
  {"General Street Old Female", "a_f_o_genstreet_01", 2, 0x61c81c85u},  // Ambient Female
  {"General Street Young Female", "a_f_m_genstreet_01", 2, 0x4b2b9d79u},  // Ambient Female
  {"Golfer Young Female", "a_f_y_golfer_01", 2, 0x7dd8fb58u},  // Ambient Female
  {"Hiker Female", "a_f_y_hiker_01", 2, 0x30830813u},  // Ambient Female
  {"Hippie Female", "a_f_y_hippie_01", 2, 0x1475b827u},  // Ambient Female
  {"Hipster Female", "a_f_y_hipster_01", 2, 0x8247d331u},  // Ambient Female
  {"Hipster Female 2", "a_f_y_hipster_02", 2, 0x97f5fe8du},  // Ambient Female
  {"Hipster Female 3", "a_f_y_hipster_03", 2, 0xa5ba9a16u},  // Ambient Female
  {"Hipster Female 4", "a_f_y_hipster_04", 2, 0x199881dcu},  // Ambient Female
  {"Indian Old Female", "a_f_o_indian_01", 2, 0xbad7bb80u},  // Ambient Female
  {"Indian Young Female", "a_f_y_indian_01", 2, 0x092d9cc1u},  // Ambient Female
  {"Jogger Female", "a_f_y_runner_01", 2, 0xc7496729u},  // Ambient Female
  {"Juggalo Female", "a_f_y_juggalo_01", 2, 0xdb134533u},  // Ambient Female
  {"Korean Female", "a_f_m_ktown_01", 2, 0x52c824deu},  // Ambient Female
  {"Korean Female 2", "a_f_m_ktown_02", 2, 0x41018151u},  // Ambient Female
  {"Korean Old Female", "a_f_o_ktown_01", 2, 0x47cf5e96u},  // Ambient Female
  {"Prologue Host Female", "a_f_m_prolhost_01", 2, 0x169bd1e1u},  // Ambient Female
  {"Rural Meth Addict Female", "a_f_y_rurmeth_01", 2, 0x3f789426u},  // Ambient Female
  {"Salton Female", "a_f_m_salton_01", 2, 0xde0e0969u},  // Ambient Female
  {"Salton Old Female", "a_f_o_salton_01", 2, 0xccff7d8au},  // Ambient Female
  {"Skater Female", "a_f_y_skater_01", 2, 0x695fe666u},  // Ambient Female
  {"Skid Row Female", "a_f_m_skidrow_01", 2, 0xb097523bu},  // Ambient Female
  {"South Central Female", "a_f_m_soucent_01", 2, 0x745855a1u},  // Ambient Female
  {"South Central Female 2", "a_f_m_soucent_02", 2, 0xf322d338u},  // Ambient Female
  {"South Central MC Female", "a_f_m_soucentmc_01", 2, 0xcde955d2u},  // Ambient Female
  {"South Central Old Female", "a_f_o_soucent_01", 2, 0x3dfa1830u},  // Ambient Female
  {"South Central Old Female 2", "a_f_o_soucent_02", 2, 0xa56de716u},  // Ambient Female
  {"South Central Young Female", "a_f_y_soucent_01", 2, 0x2c641d7au},  // Ambient Female
  {"South Central Young Female 2", "a_f_y_soucent_02", 2, 0x5a8ef9cfu},  // Ambient Female
  {"South Central Young Female 3", "a_f_y_soucent_03", 2, 0x87b25415u},  // Ambient Female
  {"Studio Party Female", "a_f_y_studioparty_01", 2, 0x44b4d748u},  // Ambient Female
  {"Studio Party Female 2", "a_f_y_studioparty_02", 2, 0x76463a5eu},  // Ambient Female
  {"Tennis Player Female", "a_f_y_tennis_01", 2, 0x550c79c6u},  // Ambient Female
  {"Topless", "a_f_y_topless_01", 2, 0x9cf26183u},  // Ambient Female
  {"Tourist Female", "a_f_m_tourist_01", 2, 0x505603b9u},  // Ambient Female
  {"Tourist Young Female", "a_f_y_tourist_01", 2, 0x563b8570u},  // Ambient Female
  {"Tourist Young Female 2", "a_f_y_tourist_02", 2, 0x9123fb40u},  // Ambient Female
  {"Tramp Female", "a_f_m_tramp_01", 2, 0x48f96f5bu},  // Ambient Female
  {"Vinewood Female", "a_f_y_vinewood_01", 2, 0x19f41f65u},  // Ambient Female
  {"Vinewood Female 2", "a_f_y_vinewood_02", 2, 0xdab6a0ebu},  // Ambient Female
  {"Vinewood Female 3", "a_f_y_vinewood_03", 2, 0x379ddab8u},  // Ambient Female
  {"Vinewood Female 4", "a_f_y_vinewood_04", 2, 0xfae46146u},  // Ambient Female
  {"Yoga Female", "a_f_y_yoga_01", 2, 0xc41b062eu},  // Ambient Female
  {"African American Male", "a_m_m_afriamer_01", 3, 0xd172497eu},  // Ambient Male
  {"Altruist Cult Mid-Age Male", "a_m_m_acult_01", 3, 0x5442c66bu},  // Ambient Male
  {"Altruist Cult Old Male", "a_m_o_acult_01", 3, 0x55446010u},  // Ambient Male
  {"Altruist Cult Old Male 2", "a_m_o_acult_02", 3, 0x4ba14ccau},  // Ambient Male
  {"Altruist Cult Young Male", "a_m_y_acult_01", 3, 0xb564882bu},  // Ambient Male
  {"Altruist Cult Young Male 2", "a_m_y_acult_02", 3, 0x80e59f2eu},  // Ambient Male
  {"Bank Robber Male", "a_m_m_bankrobber_01", 3, 0xd94dffeau},  // Ambient Male
  {"Beach Male", "a_m_m_beach_01", 3, 0x403db4fdu},  // Ambient Male
  {"Beach Male 2", "a_m_m_beach_02", 3, 0x787fa588u},  // Ambient Male
  {"Beach Muscle Male", "a_m_y_musclbeac_01", 3, 0x4b652906u},  // Ambient Male
  {"Beach Muscle Male 2", "a_m_y_musclbeac_02", 3, 0xc923247cu},  // Ambient Male
  {"Beach Old Male", "a_m_o_beach_01", 3, 0x8427d398u},  // Ambient Male
  {"Beach Old Male 2", "a_m_o_beach_02", 3, 0xc1534df2u},  // Ambient Male
  {"Beach Tramp Male", "a_m_m_trampbeac_01", 3, 0x53b57eb0u},  // Ambient Male
  {"Beach Young Male", "a_m_y_beach_01", 3, 0xd1feb884u},  // Ambient Male
  {"Beach Young Male 2", "a_m_y_beach_02", 3, 0x23c7dc11u},  // Ambient Male
  {"Beach Young Male 3", "a_m_y_beach_03", 3, 0xe7a963d9u},  // Ambient Male
  {"Beach Young Male 4", "a_m_y_beach_04", 3, 0xb91a86bcu},  // Ambient Male
  {"Beverly Hills Male", "a_m_m_bevhills_01", 3, 0x54dbee1fu},  // Ambient Male
  {"Beverly Hills Male 2", "a_m_m_bevhills_02", 3, 0x3fb5c3d3u},  // Ambient Male
  {"Beverly Hills Young Male", "a_m_y_bevhills_01", 3, 0x76284640u},  // Ambient Male
  {"Beverly Hills Young Male 2", "a_m_y_bevhills_02", 3, 0x668ba707u},  // Ambient Male
  {"Black Street Male", "a_m_y_stbla_01", 3, 0xcf92ade9u},  // Ambient Male
  {"Black Street Male 2", "a_m_y_stbla_02", 3, 0x98c7404fu},  // Ambient Male
  {"Breakdancer Male", "a_m_y_breakdance_01", 3, 0x379f9596u},  // Ambient Male
  {"Business Casual", "a_m_y_busicas_01", 3, 0x9ad32fe9u},  // Ambient Male
  {"Business Male", "a_m_m_business_01", 3, 0x7e6a64b7u},  // Ambient Male
  {"Business Young Male", "a_m_y_business_01", 3, 0xc99f21c4u},  // Ambient Male
  {"Business Young Male 2", "a_m_y_business_02", 3, 0xb3b3f5e6u},  // Ambient Male
  {"Business Young Male 3", "a_m_y_business_03", 3, 0xa1435105u},  // Ambient Male
  {"Car Club Male 1", "a_m_y_carclub_01", 3, 0x685ff8d4u},  // Ambient Male
  {"Car Club Male 2", "a_m_y_carclub_02", 3, 0xa64f74aeu},  // Ambient Male
  {"Casual Casino Guests", "a_m_y_gencaspat_01", 3, 0x9b047cdfu},  // Ambient Male
  {"Club Customer Male 1", "a_m_y_clubcust_01", 3, 0xa7b71042u},  // Ambient Male
  {"Club Customer Male 2", "a_m_y_clubcust_02", 3, 0xc62f4d32u},  // Ambient Male
  {"Club Customer Male 3", "a_m_y_clubcust_03", 3, 0xd4f5eabfu},  // Ambient Male
  {"Club Customer Male 4", "a_m_y_clubcust_04", 3, 0xe2210515u},  // Ambient Male
  {"Cyclist Male", "a_m_y_cyclist_01", 3, 0xfdc653c7u},  // Ambient Male
  {"Downhill Cyclist", "a_m_y_dhill_01", 3, 0xff3e88abu},  // Ambient Male
  {"Downtown Male", "a_m_y_downtown_01", 3, 0x2dadf4aau},  // Ambient Male
  {"East SA Male", "a_m_m_eastsa_01", 3, 0xf9a6f53fu},  // Ambient Male
  {"East SA Male 2", "a_m_m_eastsa_02", 3, 0x07dd91acu},  // Ambient Male
  {"East SA Young Male", "a_m_y_eastsa_01", 3, 0xa4471173u},  // Ambient Male
  {"East SA Young Male 2", "a_m_y_eastsa_02", 3, 0x168775f6u},  // Ambient Male
  {"Epsilon Male", "a_m_y_epsilon_01", 3, 0x77d41a3eu},  // Ambient Male
  {"Epsilon Male 2", "a_m_y_epsilon_02", 3, 0xaa82ff9bu},  // Ambient Male
  {"Farmer", "a_m_m_farmer_01", 3, 0x94562dd7u},  // Ambient Male
  {"Fat Latino Male", "a_m_m_fatlatin_01", 3, 0x61d201b3u},  // Ambient Male
  {"Formal Casino Guests", "a_m_y_smartcaspat_01", 3, 0x2102ba2au},  // Ambient Male
  {"Gay Male", "a_m_y_gay_01", 3, 0xd1cce036u},  // Ambient Male
  {"Gay Male 2", "a_m_y_gay_02", 3, 0xa5720781u},  // Ambient Male
  {"General Biker Male", "a_m_m_genbiker_01", 3, 0xdee17d7eu},  // Ambient Male
  {"General Fat Male", "a_m_m_genfat_01", 3, 0x06dd569fu},  // Ambient Male
  {"General Fat Male 2", "a_m_m_genfat_02", 3, 0x13aef042u},  // Ambient Male
  {"General Street Old Male", "a_m_o_genstreet_01", 3, 0xad54e7a8u},  // Ambient Male
  {"General Street Young Male", "a_m_y_genstreet_01", 3, 0x9877ef71u},  // Ambient Male
  {"General Street Young Male 2", "a_m_y_genstreet_02", 3, 0x3521a8d2u},  // Ambient Male
  {"Golfer Male", "a_m_m_golfer_01", 3, 0xa9eb0e42u},  // Ambient Male
  {"Golfer Young Male", "a_m_y_golfer_01", 3, 0xd71fe131u},  // Ambient Male
  {"Hasidic Jew Male", "a_m_m_hasjew_01", 3, 0x6bd9b68cu},  // Ambient Male
  {"Hasidic Jew Young Male", "a_m_y_hasjew_01", 3, 0xe16d8f01u},  // Ambient Male
  {"Hiker Male", "a_m_y_hiker_01", 3, 0x50f73c0cu},  // Ambient Male
  {"Hillbilly Male", "a_m_m_hillbilly_01", 3, 0x6c9b2849u},  // Ambient Male
  {"Hillbilly Male 2", "a_m_m_hillbilly_02", 3, 0x7b0e452fu},  // Ambient Male
  {"Hippie Male", "a_m_y_hippy_01", 3, 0x7d03e617u},  // Ambient Male
  {"Hipster Male", "a_m_y_hipster_01", 3, 0x2307a353u},  // Ambient Male
  {"Hipster Male 2", "a_m_y_hipster_02", 3, 0x14d506eeu},  // Ambient Male
  {"Hipster Male 3", "a_m_y_hipster_03", 3, 0x4e4179c6u},  // Ambient Male
  {"Indian Male", "a_m_m_indian_01", 3, 0xddcaaa2cu},  // Ambient Male
  {"Indian Young Male", "a_m_y_indian_01", 3, 0x2a22fbceu},  // Ambient Male
  {"Jetskier", "a_m_y_jetski_01", 3, 0x2db7eef3u},  // Ambient Male
  {"Jogger Male", "a_m_y_runner_01", 3, 0x25305eeeu},  // Ambient Male
  {"Jogger Male 2", "a_m_y_runner_02", 3, 0x843d9d0fu},  // Ambient Male
  {"Juggalo Male", "a_m_y_juggalo_01", 3, 0x91ca3e2cu},  // Ambient Male
  {"Korean Male", "a_m_m_ktown_01", 3, 0xd15d7e71u},  // Ambient Male
  {"Korean Old Male", "a_m_o_ktown_01", 3, 0x1536d95au},  // Ambient Male
  {"Korean Young Male", "a_m_y_ktown_01", 3, 0x1af6542cu},  // Ambient Male
  {"Korean Young Male 2", "a_m_y_ktown_02", 3, 0x297ff13fu},  // Ambient Male
  {"Latino Street Male 2", "a_m_m_stlat_02", 3, 0xc2a87702u},  // Ambient Male
  {"Latino Street Young Male", "a_m_y_stlat_01", 3, 0x8674d5fcu},  // Ambient Male
  {"Latino Young Male", "a_m_y_latino_01", 3, 0x132c1a8eu},  // Ambient Male
  {"Malibu Male", "a_m_m_malibu_01", 3, 0x2fde6eb7u},  // Ambient Male
  {"Meth Addict", "a_m_y_methhead_01", 3, 0x696be0a9u},  // Ambient Male
  {"Mexican Labourer", "a_m_m_mexlabor_01", 3, 0xb25d16b2u},  // Ambient Male
  {"Mexican Rural", "a_m_m_mexcntry_01", 3, 0xdd817eadu},  // Ambient Male
  {"Mexican Thug", "a_m_y_mexthug_01", 3, 0x3053e555u},  // Ambient Male
  {"Midlife Crisis Casino Bikers", "a_m_m_mlcrisis_01", 3, 0x5d0c5325u},  // Ambient Male
  {"Motocross Biker", "a_m_y_motox_01", 3, 0x64fdea7du},  // Ambient Male
  {"Motocross Biker 2", "a_m_y_motox_02", 3, 0x77ac8fdau},  // Ambient Male
  {"OG Boss", "a_m_m_og_boss_01", 3, 0x681bd012u},  // Ambient Male
  {"Paparazzi Male", "a_m_m_paparazzi_01", 3, 0xecca8c15u},  // Ambient Male
  {"Polynesian", "a_m_m_polynesian_01", 3, 0xa9d9b69eu},  // Ambient Male
  {"Polynesian Young", "a_m_y_polynesian_01", 3, 0x8384fc9fu},  // Ambient Male
  {"Prologue Host Male", "a_m_m_prolhost_01", 3, 0x9712c38fu},  // Ambient Male
  {"Road Cyclist", "a_m_y_roadcyc_01", 3, 0xf561a4c6u},  // Ambient Male
  {"Rural Meth Addict Male", "a_m_m_rurmeth_01", 3, 0x3bad4184u},  // Ambient Male
  {"Salton Male", "a_m_m_salton_01", 3, 0x4f2e038au},  // Ambient Male
  {"Salton Male 2", "a_m_m_salton_02", 3, 0x60f4a717u},  // Ambient Male
  {"Salton Male 3", "a_m_m_salton_03", 3, 0xb28c4a45u},  // Ambient Male
  {"Salton Male 4", "a_m_m_salton_04", 3, 0x964511b7u},  // Ambient Male
  {"Salton Old Male", "a_m_o_salton_01", 3, 0x20208e4du},  // Ambient Male
  {"Salton Young Male", "a_m_y_salton_01", 3, 0xd7606c30u},  // Ambient Male
  {"Skater Male", "a_m_m_skater_01", 3, 0xd9d7588cu},  // Ambient Male
  {"Skater Young Male", "a_m_y_skater_01", 3, 0xc1c46677u},  // Ambient Male
  {"Skater Young Male 2", "a_m_y_skater_02", 3, 0xaffac2e4u},  // Ambient Male
  {"Skid Row Male", "a_m_m_skidrow_01", 3, 0x01eea6bdu},  // Ambient Male
  {"South Central Latino Male", "a_m_m_socenlat_01", 3, 0x0b8d69e3u},  // Ambient Male
  {"South Central Male", "a_m_m_soucent_01", 3, 0x6857c9b7u},  // Ambient Male
  {"South Central Male 2", "a_m_m_soucent_02", 3, 0x9f6d37e1u},  // Ambient Male
  {"South Central Male 3", "a_m_m_soucent_03", 3, 0x8bd990bau},  // Ambient Male
  {"South Central Male 4", "a_m_m_soucent_04", 3, 0xc2fbfefeu},  // Ambient Male
  {"South Central Old Male", "a_m_o_soucent_01", 3, 0x2ad8921bu},  // Ambient Male
  {"South Central Old Male 2", "a_m_o_soucent_02", 3, 0x4086bd77u},  // Ambient Male
  {"South Central Old Male 3", "a_m_o_soucent_03", 3, 0x0e32d8d0u},  // Ambient Male
  {"South Central Young Male", "a_m_y_soucent_01", 3, 0xe716bdcbu},  // Ambient Male
  {"South Central Young Male 2", "a_m_y_soucent_02", 3, 0xaca3c8cau},  // Ambient Male
  {"South Central Young Male 3", "a_m_y_soucent_03", 3, 0xc3f0f764u},  // Ambient Male
  {"South Central Young Male 4", "a_m_y_soucent_04", 3, 0x8a3703f1u},  // Ambient Male
  {"Studio Party Male", "a_m_m_studioparty_01", 3, 0x8b996025u},  // Ambient Male
  {"Studio Party Male 2", "a_m_y_studioparty_01", 3, 0xb231229du},  // Ambient Male
  {"Sunbather Male", "a_m_y_sunbathe_01", 3, 0xb7292f0cu},  // Ambient Male
  {"Surfer", "a_m_y_surfer_01", 3, 0xeac2c7eeu},  // Ambient Male
  {"Tattoo Cust Male", "a_m_y_tattoocust_01", 3, 0x9c1f1a19u},  // Ambient Male
  {"Tennis Player Male", "a_m_m_tennis_01", 3, 0x546a5344u},  // Ambient Male
  {"Tourist Male", "a_m_m_tourist_01", 3, 0xc89f0184u},  // Ambient Male
  {"Tramp Male", "a_m_m_tramp_01", 3, 0x1ec93fd0u},  // Ambient Male
  {"Tramp Old Male", "a_m_o_tramp_01", 3, 0x174d4245u},  // Ambient Male
  {"Transvestite Male", "a_m_m_tranvest_01", 3, 0xe0e69974u},  // Ambient Male
  {"Transvestite Male 2", "a_m_m_tranvest_02", 3, 0xf70ec5c4u},  // Ambient Male
  {"Vespucci Beach Male", "a_m_y_beachvesp_01", 3, 0x7e0961b8u},  // Ambient Male
  {"Vespucci Beach Male 2", "a_m_y_beachvesp_02", 3, 0xca56fa52u},  // Ambient Male
  {"Vinewood Douche", "a_m_y_vindouche_01", 3, 0xc19377e7u},  // Ambient Male
  {"Vinewood Male", "a_m_y_vinewood_01", 3, 0x4b64199du},  // Ambient Male
  {"Vinewood Male 2", "a_m_y_vinewood_02", 3, 0x5d15bd00u},  // Ambient Male
  {"Vinewood Male 3", "a_m_y_vinewood_03", 3, 0x1fdf4294u},  // Ambient Male
  {"Vinewood Male 4", "a_m_y_vinewood_04", 3, 0x31c9e669u},  // Ambient Male
  {"White Street Male", "a_m_y_stwhi_01", 3, 0x2418c430u},  // Ambient Male
  {"White Street Male 2", "a_m_y_stwhi_02", 3, 0x36c6e98cu},  // Ambient Male
  {"Yoga Male", "a_m_y_yoga_01", 3, 0xab0a7155u},  // Ambient Male
  {"'Gay' Tony Prince", "csb_tonyprince", 4, 0x5d5f971bu},  // Cutscene
  {"Abigail Mathers", "csb_abigail", 4, 0x89768941u},  // Cutscene
  {"Agatha Baker", "csb_agatha", 4, 0x2d145a18u},  // Cutscene
  {"Agent", "csb_agent", 4, 0xd770c9b4u},  // Cutscene
  {"Agent 14", "csb_mp_agent14", 4, 0x6dbbfc8bu},  // Cutscene
  {"Agent 14 - Version 2", "csb_agent14_02", 4, 0x9ff7d1d7u},  // Cutscene
  {"Alan Jerome", "csb_alan", 4, 0x72cab667u},  // Cutscene
  {"Amanda Aged", "cs_amandatownley_02", 4, 0x3b32fb47u},  // Cutscene
  {"Amanda De Santa", "cs_amandatownley", 4, 0x95ef18e3u},  // Cutscene
  {"Andreas Sanchez", "cs_andreas", 4, 0xe7565327u},  // Cutscene
  {"Anita Mendoza", "csb_anita", 4, 0x0703f106u},  // Cutscene
  {"Anton Beaudelaire", "csb_anton", 4, 0xa5c787b6u},  // Cutscene
  {"Ashley Butler", "cs_ashley", 4, 0x26c3d079u},  // Cutscene
  {"Avery Duggan", "csb_avery", 4, 0x551cc92du},  // Cutscene
  {"Avi Schwartzman", "csb_money", 4, 0x989dfd9au},  // Cutscene
  {"Avi Schwartzman 2", "csb_avischwartzman_02", 4, 0x89fefce0u},  // Cutscene
  {"Avi Schwartzman 3", "csb_avischwartzman_03", 4, 0x17c89875u},  // Cutscene
  {"Avi Schwartzman 4", "csb_avi_04", 4, 0x37034283u},  // Cutscene
  {"Avon Hertz", "csb_avon", 4, 0x1833364du},  // Cutscene
  {"Ballas Leader", "csb_ballas_leader", 4, 0xb8a90e13u},  // Cutscene
  {"Ballas OG", "csb_ballasog", 4, 0xabef0004u},  // Cutscene
  {"Bank Manager", "cs_bankman", 4, 0x9760192eu},  // Cutscene
  {"Barry", "cs_barry", 4, 0x69591cf7u},  // Cutscene
  {"Beverly Felton", "cs_beverly", 4, 0xb46ec356u},  // Cutscene
  {"Bigfoot", "cs_orleans", 4, 0xad340f5au},  // Cutscene
  {"Billionaire Male", "csb_billionaire", 4, 0xca846157u},  // Cutscene
  {"Bogdan", "csb_bogdan", 4, 0x5f06d73du},  // Cutscene
  {"Brad", "cs_brad", 4, 0xefe5afe6u},  // Cutscene
  {"Brad's Cadaver", "cs_bradcadaver", 4, 0x7228af60u},  // Cutscene
  {"Bride", "csb_bride", 4, 0x82bf7ea1u},  // Cutscene
  {"Brucie Kibbutz", "csb_brucie2", 4, 0xc860ae15u},  // Cutscene
  {"Bryony", "csb_bryony", 4, 0x7791adddu},  // Cutscene
  {"Burger Shot Drug Worker", "csb_burgerdrug", 4, 0x8cdcc057u},  // Cutscene
  {"Call Girl 1", "csb_callgirl_01", 4, 0x6025b262u},  // Cutscene
  {"Call Girl 2", "csb_callgirl_02", 4, 0x2e714efau},  // Cutscene
  {"Car 3 Guy 1", "csb_car3guy1", 4, 0x04430687u},  // Cutscene
  {"Car 3 Guy 2", "csb_car3guy2", 4, 0x1383a508u},  // Cutscene
  {"Car Buyer", "cs_carbuyer", 4, 0x8cce790fu},  // Cutscene
  {"Casey", "cs_casey", 4, 0xea969c40u},  // Cutscene
  {"Celebrity 1", "csb_celeb_01", 4, 0x234ca435u},  // Cutscene
  {"Charlie Reed", "csb_req_officer", 4, 0x88f76b3au},  // Cutscene
  {"Charlie Reed 2", "csb_charlie_reed", 4, 0x009e2e4cu},  // Cutscene
  {"Chef", "csb_chef", 4, 0xa347ca8au},  // Cutscene
  {"Chef 3", "csb_chef_03", 4, 0x84dbf6c1u},  // Cutscene
  {"Chef Again", "csb_chef2", 4, 0xae5be23au},  // Cutscene
  {"Chinese Goon", "csb_chin_goon", 4, 0xa8c22996u},  // Cutscene
  {"Clay Simons (The Lost)", "cs_clay", 4, 0xdbcb9834u},  // Cutscene
  {"Cletus", "csb_cletus", 4, 0xcae9e5d5u},  // Cutscene
  {"Cop", "csb_cop", 4, 0x9ab35f63u},  // Cutscene
  {"Cris Formage", "cs_chrisformage", 4, 0xc1f380e6u},  // Cutscene
  {"Customer", "csb_customer", 4, 0xa44f6f8bu},  // Cutscene
  {"Dale", "cs_dale", 4, 0x0ce81655u},  // Cutscene
  {"Dave Norton", "cs_davenorton", 4, 0x8587248cu},  // Cutscene
  {"Dax", "csb_dax", 4, 0x429d6ff3u},  // Cutscene
  {"Debra", "cs_debra", 4, 0xecd04fe9u},  // Cutscene
  {"Denise", "cs_denise", 4, 0x6f802738u},  // Cutscene
  {"Denise's Friend", "csb_denise_friend", 4, 0xb58d2529u},  // Cutscene
  {"Devin", "cs_devin", 4, 0x2f016d02u},  // Cutscene
  {"Dima Popov", "csb_popov", 4, 0x617d89e2u},  // Cutscene
  {"DJ Black Madonna", "csb_djblamadon", 4, 0x6d65f972u},  // Cutscene
  {"DJ Dixon", "csb_dix", 4, 0xebe02d05u},  // Cutscene
  {"DJ Pooh", "csb_mjo", 4, 0xa0fda755u},  // Cutscene
  {"DJ Pooh 2", "csb_mjo_02", 4, 0x98f3fa18u},  // Cutscene
  {"Dom Beasley", "cs_dom", 4, 0x4772af42u},  // Cutscene
  {"Dr Dre", "csb_ary", 4, 0xb65c594eu},  // Cutscene
  {"Dr Dre 2", "csb_ary_02", 4, 0xea177cddu},  // Cutscene
  {"Dr. Friedlander", "cs_drfriedlander", 4, 0xa3a35c2fu},  // Cutscene
  {"Dr. Friedlander 2", "cs_drfriedlander_02", 4, 0xbd66a514u},  // Cutscene
  {"Drug Dealer", "csb_drugdealer", 4, 0x389258feu},  // Cutscene
  {"El Rubio", "csb_juanstrickler", 4, 0xd74b8139u},  // Cutscene
  {"English Dave", "csb_englishdave", 4, 0xd298823eu},  // Cutscene
  {"English Dave 2", "csb_englishdave_02", 4, 0xdd59656fu},  // Cutscene
  {"Epsilon Tom", "cs_tomepsilon", 4, 0x8c0fd4e2u},  // Cutscene
  {"Faber", "csb_faber_02", 4, 0x63cb1c23u},  // Cutscene
  {"Fabien", "cs_fabien", 4, 0x47035ec1u},  // Cutscene
  {"Fame Or Shame Rep", "csb_fos_rep", 4, 0x1bcc157bu},  // Cutscene
  {"Families Gang Member", "csb_ramp_gang", 4, 0xc2800dbeu},  // Cutscene
  {"Ferdinand Kerimov (Mr. K)", "cs_mrk", 4, 0xc3cc9a75u},  // Cutscene
  {"FIB Suit", "cs_fbisuit_01", 4, 0x585c0b52u},  // Cutscene
  {"Floyd Hebert", "cs_floyd", 4, 0x062547e7u},  // Cutscene
  {"Georgina Cheng", "csb_georginacheng", 4, 0x1491eabbu},  // Cutscene
  {"Gerald", "csb_g", 4, 0xa28e71d7u},  // Cutscene
  {"Golfer", "csb_golfer_a", 4, 0x7e5f1188u},  // Cutscene
  {"Golfer 2", "csb_golfer_b", 4, 0xdcedcea4u},  // Cutscene
  {"Groom", "csb_groom", 4, 0x7aab19d2u},  // Cutscene
  {"Grove Street Dealer", "csb_grove_str_dlr", 4, 0xe8594e22u},  // Cutscene
  {"Guadalope", "cs_guadalope", 4, 0x0f9513f1u},  // Cutscene
  {"GURK?", "cs_gurk", 4, 0xc314f727u},  // Cutscene
  {"Gustavo", "csb_gustavo", 4, 0x8af43d22u},  // Cutscene
  {"Hao", "csb_hao", 4, 0xec9e8f1cu},  // Cutscene
  {"Hao 2", "csb_hao_02", 4, 0xbf71ef93u},  // Cutscene
  {"Helmsman Pavel 1", "csb_helmsmanpavel", 4, 0x9f7e81f8u},  // Cutscene
  {"Helmsman Pavel 2", "csb_helmsmanpavel_02", 4, 0x5ee22d8bu},  // Cutscene
  {"Hick", "csb_ramp_hic", 4, 0x858c94b8u},  // Cutscene
  {"Hipster", "csb_ramp_hipster", 4, 0x21f58bb4u},  // Cutscene
  {"Huang", "csb_huang", 4, 0x3f6e6283u},  // Cutscene
  {"Hugh Welsh", "csb_hugh", 4, 0x6f139b54u},  // Cutscene
  {"Hunter", "cs_hunter", 4, 0x5b44892cu},  // Cutscene
  {"Imani", "csb_imani", 4, 0x7671a8f6u},  // Cutscene
  {"Imran Shinowa", "csb_imran", 4, 0xe3420bdbu},  // Cutscene
  {"Island Dj", "csb_isldj_00", 4, 0x7a5ee1a5u},  // Cutscene
  {"Island Dj 1", "csb_isldj_01", 4, 0x34dfd6a4u},  // Cutscene
  {"Island Dj 2", "csb_isldj_02", 4, 0x66143910u},  // Cutscene
  {"Island Dj 3", "csb_isldj_03", 4, 0x917b0fddu},  // Cutscene
  {"Island Dj 4", "csb_isldj_04", 4, 0xb2bc525fu},  // Cutscene
  {"Jack Howitzer", "csb_jackhowitzer", 4, 0x44bc7bb1u},  // Cutscene
  {"Jamal Amir", "csb_jamalamir", 4, 0xb3b3b7fbu},  // Cutscene
  {"Janet", "cs_janet", 4, 0x3034f9e2u},  // Cutscene
  {"Janitor", "csb_janitor", 4, 0xc2005a40u},  // Cutscene
  {"Jenette", "csb_jenettee", 4, 0xf41e3dfau},  // Cutscene
  {"Jeweller Assistant", "cs_jewelass", 4, 0x4440a804u},  // Cutscene
  {"Jimmy Boston", "cs_jimmyboston", 4, 0x039677bdu},  // Cutscene
  {"Jimmy De Santa", "cs_jimmydisanto", 4, 0xb8cc92b4u},  // Cutscene
  {"Jimmy De Santa 2", "cs_jimmydisanto2", 4, 0x6d6f811bu},  // Cutscene
  {"Jimmy Lovine 1", "csb_jio", 4, 0xa28b9e2du},  // Cutscene
  {"Jimmy Lovine 2", "csb_jio_02", 4, 0xdcb110b0u},  // Cutscene
  {"Jodi Marshall", "csb_jodimarshall", 4, 0x91dc2b69u},  // Cutscene
  {"Johnny Guns", "csb_johnny_guns", 4, 0x7da9c6a1u},  // Cutscene
  {"Johnny Klebitz", "cs_johnnyklebitz", 4, 0xfa8ab881u},  // Cutscene
  {"Josef", "cs_josef", 4, 0x459762cau},  // Cutscene
  {"Josh", "cs_josh", 4, 0x450eef9du},  // Cutscene
  {"Karen Daniels", "cs_karen_daniels", 4, 0x4baf381cu},  // Cutscene
  {"Labrat", "csb_labrat", 4, 0x58e45333u},  // Cutscene
  {"Lamar Davis", "cs_lamardavis", 4, 0x45463a0du},  // Cutscene
  {"Lamar Davis 2", "cs_lamardavis_02", 4, 0x01562e05u},  // Cutscene
  {"Lazlow", "cs_lazlow", 4, 0x38951a1bu},  // Cutscene
  {"Lazlow 2", "cs_lazlow_2", 4, 0x5f4c593du},  // Cutscene
  {"Lester Crest", "cs_lestercrest", 4, 0xb594f5c3u},  // Cutscene
  {"Lester Crest 2", "cs_lestercrest_2", 4, 0x0b63911du},  // Cutscene
  {"Lester Crest 3", "cs_lestercrest_3", 4, 0x1d953580u},  // Cutscene
  {"Life Invader", "cs_lifeinvad_01", 4, 0x72551375u},  // Cutscene
  {"Luchadora", "csb_luchadora", 4, 0x51d861f2u},  // Cutscene
  {"Magenta", "cs_magenta", 4, 0x5816c61au},  // Cutscene
  {"Manuel", "cs_manuel", 4, 0xfbb374cau},  // Cutscene
  {"Marine", "csb_ramp_marine", 4, 0x616c97b9u},  // Cutscene
  {"Marnie Allen", "cs_marnie", 4, 0x574de134u},  // Cutscene
  {"Martin Madrazo", "cs_martinmadrazo", 4, 0x43595670u},  // Cutscene
  {"Martin Madrazo 2", "cs_martinmadrazo_02", 4, 0x8e7525c3u},  // Cutscene
  {"Mary-Ann Quinn", "cs_maryann", 4, 0x0998c7adu},  // Cutscene
  {"Maude", "csb_maude", 4, 0xbcc475cbu},  // Cutscene
  {"Maude Bottom Dollar Bounties", "csb_maude_02", 4, 0x72f9a2bdu},  // Cutscene
  {"Maxim Rashkovsky", "csb_rashcosvki", 4, 0x188099a9u},  // Cutscene
  {"Merryweather Merc", "csb_mweather", 4, 0x613e626cu},  // Cutscene
  {"Mexican", "csb_ramp_mex", 4, 0xf64ed7d0u},  // Cutscene
  {"Michelle", "cs_michelle", 4, 0x70aeb9c8u},  // Cutscene
  {"Miguel Madrazo", "csb_miguelmadrazo", 4, 0xdbb17082u},  // Cutscene
  {"Milton McIlroy", "cs_milton", 4, 0xb76a330fu},  // Cutscene
  {"Mimi", "csb_mimi", 4, 0x86c1ffe8u},  // Cutscene
  {"Minuteman Joe", "cs_joeminuteman", 4, 0xf09d5e29u},  // Cutscene
  {"Molly", "cs_molly", 4, 0x45918e44u},  // Cutscene
  {"Moodyman", "csb_moodyman_02", 4, 0x8d7ee5a4u},  // Cutscene
  {"Movie Premiere Female", "cs_movpremf_01", 4, 0x4bba84d9u},  // Cutscene
  {"Movie Premiere Male", "cs_movpremmale", 4, 0x8d67ee7du},  // Cutscene
  {"Mr Faber", "csb_weiss", 4, 0xf306284bu},  // Cutscene
  {"Mrs. Phillips", "cs_mrsphillips", 4, 0xcbfda3cfu},  // Cutscene
  {"Mrs. Rackman", "csb_mrs_r", 4, 0x9d79c026u},  // Cutscene
  {"Mrs. Thornhill", "cs_mrs_thornhill", 4, 0x4f921e6eu},  // Cutscene
  {"Musician Male", "csb_musician_00", 4, 0xc7bc9e2cu},  // Cutscene
  {"Natalia", "cs_natalia", 4, 0x4efeb1f0u},  // Cutscene
  {"Nervous Ron", "cs_nervousron", 4, 0x7896da94u},  // Cutscene
  {"Nervous Ron 2", "cs_nervousron_02", 4, 0x2b94b98eu},  // Cutscene
  {"Nigel", "cs_nigel", 4, 0xe1479c0bu},  // Cutscene
  {"Old Man 1", "cs_old_man1a", 4, 0x1eec7bdcu},  // Cutscene
  {"Old Man 2", "cs_old_man2", 4, 0x98f9e770u},  // Cutscene
  {"Omega", "cs_omega", 4, 0x8b70b405u},  // Cutscene
  {"Ortega", "csb_ortega", 4, 0xc0db04cfu},  // Cutscene
  {"Oscar 1", "csb_oscar", 4, 0xf41f399bu},  // Cutscene
  {"Oscar 2", "csb_oscar_02", 4, 0xc29f7322u},  // Cutscene
  {"Paige Harris", "csb_paige", 4, 0x5b1fa0c3u},  // Cutscene
  {"Party Promoter", "csb_party_promo", 4, 0x98d8449fu},  // Cutscene
  {"Patricia", "cs_patricia", 4, 0xdf8b1301u},  // Cutscene
  {"Patricia 2", "cs_patricia_02", 4, 0x2efaa8c3u},  // Cutscene
  {"Peter Dreyfuss", "cs_dreyfuss", 4, 0x3c60a153u},  // Cutscene
  {"Porn Dude", "csb_porndudes", 4, 0x2f4afe35u},  // Cutscene
  {"Priest", "cs_priest", 4, 0x4d6de57eu},  // Cutscene
  {"Prologue Driver", "csb_prologuedriver", 4, 0xf00b49dbu},  // Cutscene
  {"Prologue Security", "csb_prolsec", 4, 0x7fa2f024u},  // Cutscene
  {"Prologue Security 2", "cs_prolsec_02", 4, 0x1e9314a2u},  // Cutscene
  {"Raf De Angelis", "csb_rafdeangelis", 4, 0x6b650016u},  // Cutscene
  {"Reporter", "csb_reporter", 4, 0x2e420a24u},  // Cutscene
  {"Rocco Pelosi", "csb_roccopelosi", 4, 0xaa64168cu},  // Cutscene
  {"Russian Drunk", "cs_russiandrunk", 4, 0x46521a32u},  // Cutscene
  {"Scott Storch (Cayo Perico)", "csb_sss", 4, 0xe0dbdc60u},  // Cutscene
  {"Screenwriter", "csb_screen_writer", 4, 0x8be12cecu},  // Cutscene
  {"Security Male", "csb_security_a", 4, 0x2bc9001cu},  // Cutscene
  {"sessanta", "csb_sessanta", 4, 0xd3bac7e0u},  // Cutscene
  {"Simeon Yetarian", "cs_siemonyetarian", 4, 0xc0937202u},  // Cutscene
  {"Soloman", "csb_sol", 4, 0x4ef92b55u},  // Cutscene
  {"Solomon Richards", "cs_solomon", 4, 0xf6d1e04eu},  // Cutscene
  {"Sound Engineer", "csb_soundeng_00", 4, 0x20606d6cu},  // Cutscene
  {"Steve Haines", "cs_stevehains", 4, 0xa4e0a1feu},  // Cutscene
  {"Stretch", "cs_stretch", 4, 0x893d6805u},  // Cutscene
  {"Stripper", "csb_stripper_01", 4, 0xaeea76b5u},  // Cutscene
  {"Stripper 2", "csb_stripper_02", 4, 0x81441b71u},  // Cutscene
  {"Tale of Us 1", "csb_talcc", 4, 0xca300478u},  // Cutscene
  {"Tale of Us 2", "csb_talmm", 4, 0xe1a0bfedu},  // Cutscene
  {"Tanisha", "cs_tanisha", 4, 0x42fe5370u},  // Cutscene
  {"Tao Cheng", "cs_taocheng", 4, 0x8864083du},  // Cutscene
  {"Tao Cheng (Casino)", "cs_taocheng2", 4, 0x26bebe36u},  // Cutscene
  {"Tao's Translator", "cs_taostranslator", 4, 0x53536529u},  // Cutscene
  {"Tao's Translator 2", "cs_taostranslator2", 4, 0xb3d82d2fu},  // Cutscene
  {"Tennis Coach", "cs_tenniscoach", 4, 0x5c26040au},  // Cutscene
  {"Terry", "cs_terry", 4, 0x3a5201c5u},  // Cutscene
  {"Thornton Duggan", "csb_thornton", 4, 0xf398da51u},  // Cutscene
  {"Tom", "cs_tom", 4, 0x69e8abc3u},  // Cutscene
  {"Tom Connors", "csb_tomcasino", 4, 0xcff0d4bbu},  // Cutscene
  {"Tonya", "csb_tonya", 4, 0x6343dd19u},  // Cutscene
  {"Tracey De Santa", "cs_tracydisanto", 4, 0x0609b130u},  // Cutscene
  {"Traffic Warden", "csb_trafficwarden", 4, 0xde2937f3u},  // Cutscene
  {"Undercover Cop", "csb_undercover", 4, 0xef785a6au},  // Cutscene
  {"United Paper Man", "cs_paper", 4, 0x6b38b8f8u},  // Cutscene
  {"Vagos Funeral Speaker", "csb_vagspeak", 4, 0x48ff4ca9u},  // Cutscene
  {"Vagos Gang Leader", "csb_vagos_leader", 4, 0x8332ebe5u},  // Cutscene
  {"Valentina", "csb_valentina", 4, 0x4c436ef0u},  // Cutscene
  {"Vernon", "csb_vernon", 4, 0xbd7713c6u},  // Cutscene
  {"Vincent", "csb_vincent_2", 4, 0xa5e08e20u},  // Cutscene
  {"Vincent (Casino)", "csb_vincent", 4, 0x1f0846a7u},  // Cutscene
  {"Vincent 4", "csb_vincent_4", 4, 0x8025c2abu},  // Cutscene
  {"Wade", "cs_wade", 4, 0xd266d9d6u},  // Cutscene
  {"Wei Cheng Sr", "cs_chengsr", 4, 0x30db9d7bu},  // Cutscene
  {"Wendy", "csb_wendy", 4, 0x55a789afu},  // Cutscene
  {"Yusuf Amir", "csb_yusufamir", 4, 0xa17ec96cu},  // Cutscene
  {"Zimbor", "cs_zimbor", 4, 0xeaacaaf0u},  // Cutscene
  {"Ballas Female", "g_f_y_ballas_01", 5, 0x158c439cu},  // Gang Female
  {"Families Female", "g_f_y_families_01", 5, 0x4e0ce5d3u},  // Gang Female
  {"Fooliganz Female", "g_f_m_fooliganz_01", 5, 0xa143cbcdu},  // Gang Female
  {"Gang Female (Import-Export)", "g_f_importexport_01", 5, 0x84a1b11au},  // Gang Female
  {"The Lost MC Female", "g_f_y_lost_01", 5, 0xfd5537deu},  // Gang Female
  {"Vagos Female", "g_f_y_vagos_01", 5, 0x5aa42c21u},  // Gang Female
  {"Armenian Boss", "g_m_m_armboss_01", 6, 0xf1e823a2u},  // Gang Male
  {"Armenian Goon", "g_m_m_armgoon_01", 6, 0xfda94268u},  // Gang Male
  {"Armenian Goon 2", "g_m_y_armgoon_02", 6, 0xc54e878au},  // Gang Male
  {"Armenian Lieutenant", "g_m_m_armlieut_01", 6, 0xe7714013u},  // Gang Male
  {"Azteca", "g_m_y_azteca_01", 6, 0x68709618u},  // Gang Male
  {"Ballas East Male", "g_m_y_ballaeast_01", 6, 0xf42ee883u},  // Gang Male
  {"Ballas Original Male", "g_m_y_ballaorig_01", 6, 0x231af63fu},  // Gang Male
  {"Ballas South Male", "g_m_y_ballasout_01", 6, 0x23b88069u},  // Gang Male
  {"Cartel Goon", "g_m_m_cartelgoons_01", 6, 0x995b3f9fu},  // Gang Male
  {"Cartel Guard 1", "g_m_m_cartelguards_01", 6, 0x7ed5ad78u},  // Gang Male
  {"Cartel Guard 2", "g_m_m_cartelguards_02", 6, 0x6c8c08e5u},  // Gang Male
  {"Casino Guests?", "g_m_m_casrn_01", 6, 0x3cd28cb3u},  // Gang Male
  {"Chemical Plant Worker", "g_m_m_chemwork_01", 6, 0xf6157d8fu},  // Gang Male
  {"Chinese Boss", "g_m_m_chiboss_01", 6, 0xb9dd0300u},  // Gang Male
  {"Chinese Goon", "g_m_m_chigoon_01", 6, 0x7e4f763fu},  // Gang Male
  {"Chinese Goon 2", "g_m_m_chigoon_02", 6, 0xff71f826u},  // Gang Male
  {"Chinese Goon Older", "g_m_m_chicold_01", 6, 0x106d9a99u},  // Gang Male
  {"Families CA Male", "g_m_y_famca_01", 6, 0xe83b93b7u},  // Gang Male
  {"Families DNF Male", "g_m_y_famdnf_01", 6, 0xdb729238u},  // Gang Male
  {"Families FOR Male", "g_m_y_famfor_01", 6, 0x84302b09u},  // Gang Male
  {"Fooliganz Male", "g_m_m_fooliganz_01", 6, 0x24f8ace6u},  // Gang Male
  {"Friedlander Goon", "g_m_m_friedlandergoons_01", 6, 0x04d2c4ecu},  // Gang Male
  {"Gang Male (Import-Export)", "g_m_importexport_01", 6, 0xbca2cceau},  // Gang Male
  {"Gang Prisoner Male", "g_m_m_prisoners_01", 6, 0x21b4080fu},  // Gang Male
  {"Gang Slasher Male", "g_m_m_slasher_01", 6, 0x277e179cu},  // Gang Male
  {"Generic Thug", "g_m_m_genthug_01", 6, 0xd303008bu},  // Gang Male
  {"Goon", "g_m_m_goons_01", 6, 0x61ecd362u},  // Gang Male
  {"KnoWay Goon", "g_m_m_knoway_01", 6, 0x0ac290e2u},  // Gang Male
  {"Korean Boss", "g_m_m_korboss_01", 6, 0x352a026fu},  // Gang Male
  {"Korean Lieutenant", "g_m_y_korlieut_01", 6, 0x7ccbe17au},  // Gang Male
  {"Korean Young Male", "g_m_y_korean_01", 6, 0x247502a9u},  // Gang Male
  {"Korean Young Male 2", "g_m_y_korean_02", 6, 0x8fedd989u},  // Gang Male
  {"Mara Grande Gang Male", "g_m_m_maragrande_01", 6, 0x944979a8u},  // Gang Male
  {"Mexican Boss", "g_m_m_mexboss_01", 6, 0x5761f4adu},  // Gang Male
  {"Mexican Boss 2", "g_m_m_mexboss_02", 6, 0x4914d813u},  // Gang Male
  {"Mexican Gang Member", "g_m_y_mexgang_01", 6, 0xbddd5546u},  // Gang Male
  {"Mexican Goon", "g_m_y_mexgoon_01", 6, 0x26ef3426u},  // Gang Male
  {"Mexican Goon 2", "g_m_y_mexgoon_02", 6, 0x31a3498eu},  // Gang Male
  {"Mexican Goon 3", "g_m_y_mexgoon_03", 6, 0x964d12dcu},  // Gang Male
  {"Polynesian Goon", "g_m_y_pologoon_01", 6, 0x4f3fba06u},  // Gang Male
  {"Polynesian Goon 2", "g_m_y_pologoon_02", 6, 0xa2e86156u},  // Gang Male
  {"Salvadoran Boss", "g_m_y_salvaboss_01", 6, 0x905ce0cau},  // Gang Male
  {"Salvadoran Goon", "g_m_y_salvagoon_01", 6, 0x278c8cb7u},  // Gang Male
  {"Salvadoran Goon 2", "g_m_y_salvagoon_02", 6, 0x3273a285u},  // Gang Male
  {"Salvadoran Goon 3", "g_m_y_salvagoon_03", 6, 0x03b8c510u},  // Gang Male
  {"Street Punk", "g_m_y_strpunk_01", 6, 0xfd1c49bbu},  // Gang Male
  {"Street Punk 2", "g_m_y_strpunk_02", 6, 0x0da1eac6u},  // Gang Male
  {"The Lost MC Male", "g_m_y_lost_01", 6, 0x4f46d607u},  // Gang Male
  {"The Lost MC Male 2", "g_m_y_lost_02", 6, 0x3d843282u},  // Gang Male
  {"The Lost MC Male 3", "g_m_y_lost_03", 6, 0x32b11cdcu},  // Gang Male
  {"Undead Mage", "g_f_m_undeadmage", 6, 0x70f50897u},  // Gang Male
  {"Abigail Mathers", "ig_abigail", 7, 0x400aec41u},  // Story
  {"Acid Lab Cook", "ig_acidlabcook", 7, 0xf977b829u},  // Story
  {"Agatha Baker", "ig_agatha", 7, 0x6e99bfc8u},  // Story
  {"Agent 14", "ig_mp_agent14", 7, 0xfbf98469u},  // Story
  {"Agent 14 - Version 2", "ig_agent14_02", 7, 0x1e5280dbu},  // Story
  {"Agent Female", "ig_agent_02", 7, 0x46850b27u},  // Story
  {"Agent Male", "ig_agent", 7, 0x246af208u},  // Story
  {"Ahron Ward (Chop Shop)", "ig_ahronward", 7, 0x37411fc7u},  // Story
  {"Amanda De Santa", "ig_amandatownley", 7, 0x6d1e15f7u},  // Story
  {"Andreas Sanchez", "ig_andreas", 7, 0x47e4eea0u},  // Story
  {"Arms Manufacturer 1", "ig_armsmanufac_01", 7, 0x3b98622eu},  // Story
  {"Ashley Butler", "ig_ashley", 7, 0x7ef440dbu},  // Story
  {"Avery Duggan", "ig_avery", 7, 0xb8133f6fu},  // Story
  {"Avi Schawrtzman", "ig_avischwartzman_02", 7, 0xdea6e105u},  // Story
  {"Avi Schawrtzman", "ig_money", 7, 0x37facda6u},  // Story
  {"Avi Schwartzman 3", "ig_avischwartzman_03", 7, 0x7d311e13u},  // Story
  {"Avi Schwartzman 4", "ig_avi_04", 7, 0xcf1a2f7bu},  // Story
  {"Avon Hertz", "ig_avon", 7, 0xfce270c2u},  // Story
  {"Ballas Leader", "ig_ballas_leader", 7, 0xdb41b4efu},  // Story
  {"Ballas OG", "ig_ballasog", 7, 0xa70b4a92u},  // Story
  {"Bank Manager", "ig_bankman", 7, 0x909d9e7fu},  // Story
  {"Barry", "ig_barry", 7, 0x2f8845a3u},  // Story
  {"Benny", "ig_benny", 7, 0xc4b715d2u},  // Story
  {"Benny (Los Santos Tuners)", "ig_benny_02", 7, 0x73d1907bu},  // Story
  {"Best Man", "ig_bestmen", 7, 0x5746cd96u},  // Story
  {"Beverly Felton", "ig_beverly", 7, 0xbda21e5cu},  // Story
  {"Bigfoot / Sasquash", "ig_orleans", 7, 0x61d4c771u},  // Story
  {"Billionaire", "ig_billionaire", 7, 0x01ad5181u},  // Story
  {"Bottom Dollar Bounty 1", "ig_bountytarget_01", 7, 0xa4d7a69bu},  // Story
  {"Bottom Dollar Bounty 2", "ig_bountytarget_02", 7, 0x5dd718a3u},  // Story
  {"Bottom Dollar Bounty 3", "ig_bountytarget_03", 7, 0x8f90fc16u},  // Story
  {"Bottom Dollar Bounty 4", "ig_bountytarget_04", 7, 0xe9c4b074u},  // Story
  {"Bottom Dollar Bounty 5", "ig_bountytarget_05", 7, 0xdbff14e9u},  // Story
  {"Bottom Dollar Bounty 6", "ig_bountytarget_06", 7, 0x98b08e4du},  // Story
  {"Brad", "ig_brad", 7, 0xbdbb4922u},  // Story
  {"Bride", "ig_bride", 7, 0x6162ec47u},  // Story
  {"Brucie Kibbutz", "ig_brucie2", 7, 0xe80e9160u},  // Story
  {"Call Girl", "ig_callgirl_01", 7, 0xab3739cfu},  // Story
  {"Call Girl 2", "ig_callgirl_02", 7, 0x92100781u},  // Story
  {"Car 3 Guy 1", "ig_car3guy1", 7, 0x84f9e937u},  // Story
  {"Car 3 Guy 2", "ig_car3guy2", 7, 0x75c34acau},  // Story
  {"Casey", "ig_casey", 7, 0xe0fa2554u},  // Story
  {"Celeb 1", "ig_celeb_01", 7, 0xdb1cf044u},  // Story
  {"Charlie Reed", "ig_req_officer", 7, 0xeb176014u},  // Story
  {"Charlie Reed 2", "ig_charlie_reed", 7, 0x6c6428adu},  // Story
  {"Chef", "ig_chef", 7, 0x49eadbf6u},  // Story
  {"Chef 2", "ig_chef2", 7, 0x85889ac3u},  // Story
  {"Chef 3", "ig_chef_03", 7, 0xf6b39bd3u},  // Story
  {"Clay Jackson (The Pain Giver)", "ig_claypain", 7, 0x9d0087a8u},  // Story
  {"Clay Simons (The Lost)", "ig_clay", 7, 0x6ccfe08au},  // Story
  {"Cletus", "ig_cletus", 7, 0xe6631195u},  // Story
  {"Cris Formage", "ig_chrisformage", 7, 0x286e54a7u},  // Story
  {"Dale", "ig_dale", 7, 0x467415e9u},  // Story
  {"Dave Norton", "ig_davenorton", 7, 0x15cd4c33u},  // Story
  {"Dax", "ig_dax", 7, 0xf16844ecu},  // Story
  {"Denise", "ig_denise", 7, 0x820b33bdu},  // Story
  {"Devin", "ig_devin", 7, 0x7461a0b0u},  // Story
  {"Dima Popov", "ig_popov", 7, 0x267630feu},  // Story
  {"Dixon", "ig_dix", 7, 0xfad0f28du},  // Story
  {"DJ Aurelia", "ig_djtalaurelia", 7, 0xb12c0a74u},  // Story
  {"DJ Black Madonna", "ig_djblamadon", 7, 0xfb7c0c65u},  // Story
  {"DJ Dixon Manager", "ig_djdixmanager", 7, 0xfb9cf1beu},  // Story
  {"DJ Fotios", "ig_djsolfotios", 7, 0x49fec1f9u},  // Story
  {"DJ Ignazio", "ig_djtalignazio", 7, 0xa62549c9u},  // Story
  {"DJ Jakob", "ig_djsoljakob", 7, 0x9431f54bu},  // Story
  {"DJ Mike T", "ig_djsolmike", 7, 0x2f6a53fau},  // Story
  {"DJ Pooh", "ig_mjo", 7, 0x2d5db362u},  // Story
  {"DJ Pooh 2", "ig_mjo_02", 7, 0x38c749c4u},  // Story
  {"DJ Rob T", "ig_djsolrobt", 7, 0x47386c04u},  // Story
  {"DJ Rupert", "ig_djblamrupert", 7, 0x367ba706u},  // Story
  {"DJ Ryan H", "ig_djblamryanh", 7, 0x17df1373u},  // Story
  {"DJ Ryan S", "ig_djblamryans", 7, 0xb642503fu},  // Story
  {"Dom Beasley", "ig_dom", 7, 0x9c2db088u},  // Story
  {"Dr Dre", "ig_ary", 7, 0xcf0c7037u},  // Story
  {"Dr Dre", "ig_ary_02", 7, 0x879f366fu},  // Story
  {"Dr. Friedlander", "ig_drfriedlander", 7, 0xcbfc0df5u},  // Story
  {"Dr. Friedlander 2", "ig_drfriedlander_02", 7, 0xa07fed91u},  // Story
  {"Drugdealer", "ig_drugdealer", 7, 0x1f0ca79du},  // Story
  {"English Dave", "ig_englishdave", 7, 0x0c3ceb0cu},  // Story
  {"English Dave 2", "ig_englishdave_02", 7, 0x35ffa54au},  // Story
  {"Entourage Female 1", "ig_entourage_a", 7, 0x19f5ced2u},  // Story
  {"Entourage Female 2", "ig_entourage_b", 7, 0xc866abb5u},  // Story
  {"Epsilon Tom", "ig_tomepsilon", 7, 0xcd777aaau},  // Story
  {"Faber", "ig_faber_02", 7, 0x1d61de8du},  // Story
  {"Fabien", "ig_fabien", 7, 0xd090c350u},  // Story
  {"Families Gang Member?", "ig_ramp_gang", 7, 0xe52e126cu},  // Story
  {"Ferdinand Kerimov (Mr. K)", "ig_mrk", 7, 0xeddcab6du},  // Story
  {"FIB Leader", "ig_fibleader_01", 7, 0x392373abu},  // Story
  {"FIB Suit", "ig_fbisuit_01", 7, 0x3ae4a33bu},  // Story
  {"Floyd Hebert", "ig_floyd", 7, 0xb1b196b2u},  // Story
  {"Fooliganz 2 Female", "ig_fooliganz_02", 7, 0x384d56fcu},  // Story
  {"Fooliganz Female", "ig_fooliganz_01", 7, 0xe313ac8au},  // Story
  {"Furry", "ig_furry", 7, 0x50262db9u},  // Story
  {"Generic DJ", "ig_djgeneric_01", 7, 0x99d4a44du},  // Story
  {"Georgina Cheng", "ig_georginacheng", 7, 0xef4bab2fu},  // Story
  {"Gerald", "ig_g", 7, 0x841ba933u},  // Story
  {"Golfer Male", "ig_golfer_a", 7, 0x3f9b1a4du},  // Story
  {"Golfer Male 2", "ig_golfer_b", 7, 0x6ecc78afu},  // Story
  {"Groom", "ig_groom", 7, 0xfece8b85u},  // Story
  {"Guadalope", "ig_guadalope", 7, 0x9ccb9689u},  // Story
  {"Gun Van Seller", "ig_gunvanseller", 7, 0x5aa61d4eu},  // Story
  {"Gustavo", "ig_gustavo", 7, 0xb585b217u},  // Story
  {"Gustavo 2", "ig_gustavo_02", 7, 0xaebc2033u},  // Story
  {"Hao", "ig_hao", 7, 0x65978363u},  // Story
  {"Hao", "ig_hao_02", 7, 0xf0837160u},  // Story
  {"Helmsman Pavel 1", "ig_helmsmanpavel", 7, 0xd7c1e2b1u},  // Story
  {"Helmsman Pavel 2", "ig_helmsmanpavel_02", 7, 0x80e61f8fu},  // Story
  {"Hick", "ig_ramp_hic", 7, 0x45753032u},  // Story
  {"Hippy Leader", "ig_hippyleader", 7, 0x783bc80fu},  // Story
  {"Hipster", "ig_ramp_hipster", 7, 0xdeef9f6eu},  // Story
  {"Huang", "ig_huang", 7, 0xbfd2a133u},  // Story
  {"Hunter", "ig_hunter", 7, 0xce1324deu},  // Story
  {"Imani", "ig_imani", 7, 0x2e0a4f4au},  // Story
  {"Island Dj", "ig_isldj_00", 7, 0xe2a32e68u},  // Story
  {"Island Dj 1", "ig_isldj_01", 7, 0x6f4747ceu},  // Story
  {"Island Dj 2", "ig_isldj_02", 7, 0x5d1da37bu},  // Story
  {"Island Dj 3", "ig_isldj_03", 7, 0x13360fa9u},  // Story
  {"Island Dj 4", "ig_isldj_04", 7, 0x806e6a1cu},  // Story
  {"Island Dj 4D", "ig_isldj_04_d_01", 7, 0xb193bd6au},  // Story
  {"Island Dj 4D2", "ig_isldj_04_d_02", 7, 0xfdf6562eu},  // Story
  {"Island Dj 4E", "ig_isldj_04_e_01", 7, 0x232d795du},  // Story
  {"Jackie", "ig_jackie", 7, 0x799e61f6u},  // Story
  {"Jamal Amir", "ig_jamalamir", 7, 0x3c4b0062u},  // Story
  {"Janet", "ig_janet", 7, 0x0d6d9c49u},  // Story
  {"Jay Norris", "ig_jay_norris", 7, 0x7a32ee74u},  // Story
  {"Jay Walker", "ig_jaywalker", 7, 0x4c828695u},  // Story
  {"Jenette", "ig_jenettee", 7, 0x56dce770u},  // Story
  {"Jeweller Assistant", "ig_jewelass", 7, 0x0f5d26bbu},  // Story
  {"Jimmy Boston", "ig_jimmyboston", 7, 0xeda0082du},  // Story
  {"Jimmy Boston 2", "ig_jimmyboston_02", 7, 0x43b59f1cu},  // Story
  {"Jimmy De Santa", "ig_jimmydisanto", 7, 0x570462b9u},  // Story
  {"Jimmy De Santa 2", "ig_jimmydisanto2", 7, 0x842dc2d6u},  // Story
  {"Jimmy Lovine", "ig_jio_02", 7, 0xd047ee3eu},  // Story
  {"Jimmy Lovine", "ig_jio", 7, 0x73775f3fu},  // Story
  {"Jodi Marshall", "ig_jodimarshall", 7, 0x3e387198u},  // Story
  {"Johnny Guns", "ig_johnny_guns", 7, 0x27474ffau},  // Story
  {"Johnny Klebitz", "ig_johnnyklebitz", 7, 0x87ca80aeu},  // Story
  {"Josef", "ig_josef", 7, 0xe11a9fb4u},  // Story
  {"Josh", "ig_josh", 7, 0x799e9eeeu},  // Story
  {"Juan Strickler", "ig_juanstrickler", 7, 0x1e3e327du},  // Story
  {"Karen Daniels", "ig_karen_daniels", 7, 0xeb51d959u},  // Story
  {"Kaylee", "ig_kaylee", 7, 0xa7810923u},  // Story
  {"Kerry McIntosh", "ig_kerrymcintosh", 7, 0x5b3bd90du},  // Story
  {"Kerry McIntosh 2", "ig_kerrymcintosh_02", 7, 0xd842be92u},  // Story
  {"Labrat", "ig_labrat", 7, 0x9fdd5dd2u},  // Story
  {"Lacy Jones 2", "ig_lacey_jones_02", 7, 0xcc36beecu},  // Story
  {"Lamar Davis", "ig_lamardavis", 7, 0x65b93076u},  // Story
  {"Lamar Davis 2", "ig_lamardavis_02", 7, 0x1924a05eu},  // Story
  {"Lazlow", "ig_lazlow", 7, 0xdfe443e5u},  // Story
  {"Lazlow 2", "ig_lazlow_2", 7, 0x850446ecu},  // Story
  {"Lester Crest", "ig_lestercrest", 7, 0x4da6e849u},  // Story
  {"Lester Crest 2", "ig_lestercrest_2", 7, 0x6e42fd26u},  // Story
  {"Lester Crest 3", "ig_lestercrest_3", 7, 0x77fe10a4u},  // Story
  {"Life Invader", "ig_lifeinvad_01", 7, 0x5389a93cu},  // Story
  {"Life Invader 2", "ig_lifeinvad_02", 7, 0x27bd51d4u},  // Story
  {"Lil Dee", "ig_lildee", 7, 0xc80df962u},  // Story
  {"luchadora", "ig_luchadora", 7, 0xf82e3a89u},  // Story
  {"Lupe", "ig_warehouseboss", 7, 0x42107ca3u},  // Story
  {"Madrazo's Driver", "ig_madrazodriver_01", 7, 0x596715cbu},  // Story
  {"Magenta", "ig_magenta", 7, 0xfcdc910au},  // Story
  {"Malc", "ig_malc", 7, 0xf1bca919u},  // Story
  {"Manuel", "ig_manuel", 7, 0xfd418e10u},  // Story
  {"Marnie Allen", "ig_marnie", 7, 0x188232d0u},  // Story
  {"Martin Madrazo 2", "ig_martinmadrazo_02", 7, 0xf2be4395u},  // Story
  {"Mary-Ann Quinn", "ig_maryann", 7, 0xa36f9806u},  // Story
  {"Mason Duggan", "ig_mason_duggan", 7, 0x49004f25u},  // Story
  {"Maude", "ig_maude", 7, 0x3be8287eu},  // Story
  {"Maxim Rashkovsky", "ig_rashcosvki", 7, 0x380c4de6u},  // Story
  {"Mechanic (Vinewood Car Club)", "ig_mechanic_03", 7, 0x50711c22u},  // Story
  {"Mechanic Female (Red's Auto Parts)", "ig_mechanic_02", 7, 0x5ec7b8cfu},  // Story
  {"Mechanic Male (Red's Auto Parts)", "ig_mechanic_01", 7, 0x1cc234a5u},  // Story
  {"Mexican", "ig_ramp_mex", 7, 0xe6ac74a4u},  // Story
  {"Michelle", "ig_michelle", 7, 0xbf9672f4u},  // Story
  {"Miguel Madrazo", "ig_miguelmadrazo", 7, 0xa5cd7cd8u},  // Story
  {"Milton McIlroy", "ig_milton", 7, 0xcb3059b2u},  // Story
  {"Mimi", "ig_mimi", 7, 0x784f9c95u},  // Story
  {"Minuteman Joe", "ig_joeminuteman", 7, 0xbe204c9bu},  // Story
  {"Molly", "ig_molly", 7, 0xaf03dde1u},  // Story
  {"Moodyman", "ig_moodyman_02", 7, 0x97d144b3u},  // Story
  {"Mr Faber", "ig_weiss", 7, 0x7bb69c35u},  // Story
  {"Mrs. Phillips", "ig_mrsphillips", 7, 0x3862eea8u},  // Story
  {"Mrs. Thornhill", "ig_mrs_thornhill", 7, 0x1e04a96bu},  // Story
  {"Murph", "ig_maudebf", 7, 0x5e3cebdau},  // Story
  {"Musician 00", "ig_musician_00", 7, 0x23791abfu},  // Story
  {"Natalia", "ig_natalia", 7, 0xde17dd3bu},  // Story
  {"Nervous Ron", "ig_nervousron", 7, 0xbd006af1u},  // Story
  {"Nervous Ron 2", "ig_nervousron_02", 7, 0x04757feau},  // Story
  {"Nigel", "ig_nigel", 7, 0xc8b7167du},  // Story
  {"O'Neil Brothers", "ig_oneil", 7, 0x2dc6d3e7u},  // Story
  {"Old Man 1", "ig_old_man1a", 7, 0x719d27f4u},  // Story
  {"Old Man 2", "ig_old_man2", 7, 0xef154c47u},  // Story
  {"Old Rich Guy", "ig_oldrichguy", 7, 0x3c04504au},  // Story
  {"Omega", "ig_omega", 7, 0x60e6a7d8u},  // Story
  {"Ortega", "ig_ortega", 7, 0x26a562b7u},  // Story
  {"Oscar 2", "ig_oscar_02", 7, 0x3e257dbcu},  // Story
  {"Paige Harris", "ig_paige", 7, 0x154fcf3fu},  // Story
  {"Party Promoter", "ig_party_promo", 7, 0x85b8a435u},  // Story
  {"Patricia", "ig_patricia", 7, 0xc56e118cu},  // Story
  {"Patricia 2", "ig_patricia_02", 7, 0xc3114cb1u},  // Story
  {"Pernell Moss", "ig_pernell_moss", 7, 0x85808866u},  // Story
  {"Peter Dreyfuss", "ig_dreyfuss", 7, 0xda890932u},  // Story
  {"Pilot", "ig_pilot", 7, 0x864ed68eu},  // Story
  {"Pilot 2", "ig_pilot_02", 7, 0x0aebdf93u},  // Story
  {"Priest", "ig_priest", 7, 0x6437e77du},  // Story
  {"Prologue Security 2", "ig_prolsec_02", 7, 0x27b3ad75u},  // Story
  {"Raf De Angelis", "ig_rafdeangelis", 7, 0x268c057bu},  // Story
  {"Rocco Pelosi", "ig_roccopelosi", 7, 0xd5ba52ffu},  // Story
  {"Rooster McCraw", "ig_roostermccraw", 7, 0x7c5a8701u},  // Story
  {"Russian Drunk", "ig_russiandrunk", 7, 0x3d0a5eb1u},  // Story
  {"Sacha Yetarian", "ig_sacha", 7, 0x5802d9f5u},  // Story
  {"Scott Storch", "ig_sss", 7, 0x3b18e305u},  // Story
  {"Screenwriter", "ig_screen_writer", 7, 0xffe63677u},  // Story
  {"Security Male", "ig_security_a", 7, 0x2f4e5c7bu},  // Story
  {"Sessanta", "ig_sessanta", 7, 0x371b9da9u},  // Story
  {"Simeon Yetarian", "ig_siemonyetarian", 7, 0x4c7b2f05u},  // Story
  {"Skeleton", "ig_skeleton_01", 7, 0xb0aaf8c0u},  // Story
  {"Soloman", "ig_sol", 7, 0xe1ab915cu},  // Story
  {"Soloman Manager", "ig_djsolmanager", 7, 0x7e924255u},  // Story
  {"Solomon Richards", "ig_solomon", 7, 0x86bdfe26u},  // Story
  {"Sound Engineer Female", "ig_soundeng_00", 7, 0xda3bdde8u},  // Story
  {"Steve Haines", "ig_stevehains", 7, 0x382121c8u},  // Story
  {"Stretch", "ig_stretch", 7, 0x36984358u},  // Story
  {"Sub Crew Head", "ig_subcrewhead", 7, 0xe29caa7du},  // Story
  {"Tale of Us 1", "ig_talcc", 7, 0xe43422a3u},  // Story
  {"Tale of Us 2", "ig_talmm", 7, 0x46764719u},  // Story
  {"Talina", "ig_talina", 7, 0xe793c8e8u},  // Story
  {"Tanisha", "ig_tanisha", 7, 0x0d810489u},  // Story
  {"Tao Cheng", "ig_taocheng", 7, 0xdc5c5ea5u},  // Story
  {"Tao Cheng (Casino)", "ig_taocheng2", 7, 0x59c62b90u},  // Story
  {"Tao's Translator", "ig_taostranslator", 7, 0x7c851464u},  // Story
  {"Tao's Translator (Casino)", "ig_taostranslator2", 7, 0xe433179fu},  // Story
  {"Tennis Coach", "ig_tenniscoach", 7, 0xa23b5f57u},  // Story
  {"Terry", "ig_terry", 7, 0x67000b94u},  // Story
  {"Thornton Duggan", "ig_thornton", 7, 0x93fecbd7u},  // Story
  {"Tom Connors", "ig_tomcasino", 7, 0x035456a4u},  // Story
  {"Tony Prince", "ig_tonyprince", 7, 0x2d6897b5u},  // Story
  {"Tonya", "ig_tonya", 7, 0xcac85344u},  // Story
  {"Tracey De Santa", "ig_tracydisanto", 7, 0xde352a35u},  // Story
  {"Traffic Warden", "ig_trafficwarden", 7, 0x5719786du},  // Story
  {"Tyler Dixon", "ig_tylerdix", 7, 0x5265f707u},  // Story
  {"Tyler Dixon 2", "ig_tylerdix_02", 7, 0x5a185477u},  // Story
  {"United Paper Man", "ig_paper", 7, 0x999b00c6u},  // Story
  {"Vagos Funeral Speaker", "ig_vagspeak", 7, 0xf9fd068cu},  // Story
  {"Vagos Gang Leader", "ig_vagos_leader", 7, 0x837b64deu},  // Story
  {"Valentina", "ig_valentina", 7, 0x60b845b1u},  // Story
  {"Valentine's Cheater Male", "ig_valencheat", 7, 0xc48d9f3bu},  // Story
  {"Vernon", "ig_vernon", 7, 0xcdb291a2u},  // Story
  {"Vincent", "ig_vincent", 7, 0x2be886b2u},  // Story
  {"Vincent 2", "ig_vincent_2", 7, 0x0bc4bdd3u},  // Story
  {"Vincent 3", "ig_vincent_3", 7, 0x15add1a5u},  // Story
  {"Vincent 4", "ig_vincent_4", 7, 0x69287899u},  // Story
  {"Wade", "ig_wade", 7, 0x92991b72u},  // Story
  {"Wei Cheng", "ig_chengsr", 7, 0xaae4ea7bu},  // Story
  {"Wendy", "ig_wendy", 7, 0x6e47a411u},  // Story
  {"Yusuf Amir", "ig_yusufamir", 7, 0x5fd9df6cu},  // Story
  {"Zimbor", "ig_zimbor", 7, 0x0b34d6f5u},  // Story
  {"Zombie DJ", "ig_zombie_dj_01", 7, 0xbe5f26d7u},  // Story
  {"Armoured Van Security Male", "mp_s_m_armoured_01", 8, 0xcdef5408u},  // Multiplayer
  {"Avon Goon", "mp_m_avongoon", 8, 0x9c13cb95u},  // Multiplayer
  {"Benny Mechanic (Female)", "mp_f_bennymech_01", 8, 0x7f81b0bdu},  // Multiplayer
  {"Biker Cocaine Female", "mp_f_cocaine_01", 8, 0x4b657af8u},  // Multiplayer
  {"Biker Cocaine Male", "mp_m_cocaine_01", 8, 0x56d38f95u},  // Multiplayer
  {"Biker Counterfeit Female", "mp_f_counterfeit_01", 8, 0xb788f1f5u},  // Multiplayer
  {"Biker Counterfeit Male", "mp_m_counterfeit_01", 8, 0x9855c974u},  // Multiplayer
  {"Biker Forgery Female", "mp_f_forgery_01", 8, 0x781a3cf8u},  // Multiplayer
  {"Biker Forgery Male", "mp_m_forgery_01", 8, 0x613e709bu},  // Multiplayer
  {"Biker Meth Female", "mp_f_meth_01", 8, 0xd2b27ec1u},  // Multiplayer
  {"Biker Meth Male", "mp_m_meth_01", 8, 0xedb42f3fu},  // Multiplayer
  {"Biker Weed Female", "mp_f_weed_01", 8, 0xb26573a3u},  // Multiplayer
  {"Biker Weed Male", "mp_m_weed_01", 8, 0x917ed459u},  // Multiplayer
  {"Boat-Staff Female", "mp_f_boatstaff_01", 8, 0x3293b9ceu},  // Multiplayer
  {"Boat-Staff Male", "mp_m_boatstaff_01", 8, 0xc85f0a88u},  // Multiplayer
  {"Bogdan Goon", "mp_m_bogdangoon", 8, 0x4d5696f7u},  // Multiplayer
  {"Claude Speed", "mp_m_claude_01", 8, 0xc0f371b7u},  // Multiplayer
  {"Clubhouse Bar Female", "mp_f_chbar_01", 8, 0xc3f6e385u},  // Multiplayer
  {"Dead Hooker", "mp_f_deadhooker", 8, 0x73dea88bu},  // Multiplayer
  {"Ex-Army Male", "mp_m_exarmy_01", 8, 0x45348dbbu},  // Multiplayer
  {"Executive PA Female", "mp_f_execpa_01", 8, 0x432ca064u},  // Multiplayer
  {"Executive PA Female 2", "mp_f_execpa_02", 8, 0x5972ccf0u},  // Multiplayer
  {"Executive PA Male", "mp_m_execpa_01", 8, 0x3e8417bcu},  // Multiplayer
  {"Families DD Male", "mp_m_famdd_01", 8, 0x33a464e5u},  // Multiplayer
  {"FIB Security", "mp_m_fibsec_01", 8, 0x5cdef405u},  // Multiplayer
  {"Heli-Staff Female", "mp_f_helistaff_01", 8, 0x19b6ff06u},  // Multiplayer
  {"John Marston", "mp_m_marston_01", 8, 0x38430167u},  // Multiplayer
  {"Misty", "mp_f_misty_01", 8, 0xd128ff9du},  // Multiplayer
  {"Niko Bellic", "mp_m_niko_01", 8, 0xeedacfc9u},  // Multiplayer
  {"Office Garage Mechanic (Female)", "mp_f_cardesign_01", 8, 0x242c34a7u},  // Multiplayer
  {"Pros", "mp_g_m_pros_01", 8, 0x6c9dd7c9u},  // Multiplayer
  {"Securoserve Guard (Male)", "mp_m_securoguard_01", 8, 0xda2c984eu},  // Multiplayer
  {"Shopkeeper (Male)", "mp_m_shopkeep_01", 8, 0x18ce57d0u},  // Multiplayer
  {"Stripper Lite (Female)", "mp_f_stripperlite", 8, 0x2970a494u},  // Multiplayer
  {"Vagos Funeral", "mp_m_g_vagfun_01", 8, 0xc4a617bdu},  // Multiplayer
  {"Warehouse Mechanic (Male)", "mp_m_waremech_01", 8, 0xf7a74139u},  // Multiplayer
  {"Weapon Exp (Male)", "mp_m_weapexp_01", 8, 0x36ea5b09u},  // Multiplayer
  {"Weapon Work (Male)", "mp_m_weapwork_01", 8, 0x4186506eu},  // Multiplayer
  {"Air Hostess", "s_f_y_airhostess_01", 9, 0x5d71a46fu},  // Scenario Female
  {"Autoshop Worker Female", "s_f_m_autoshop_01", 9, 0x00bd1f24u},  // Scenario Female
  {"Barber Female", "s_f_m_fembarber", 9, 0x163b875bu},  // Scenario Female
  {"Bartender", "s_f_y_bartender_01", 9, 0x780c01bdu},  // Scenario Female
  {"Baywatch Female", "s_f_y_baywatch_01", 9, 0x4a8e5536u},  // Scenario Female
  {"Beach Bar Staff", "s_f_y_beachbarstaff_01", 9, 0xc2e31a0au},  // Scenario Female
  {"Casino Staff", "s_f_y_casino_01", 9, 0xbc92bed5u},  // Scenario Female
  {"Club Bartender Female", "s_f_y_clubbar_01", 9, 0xc126394bu},  // Scenario Female
  {"Club Bartender Female 2", "s_f_y_clubbar_02", 9, 0x55c5627bu},  // Scenario Female
  {"Cop Female", "s_f_y_cop_01", 9, 0x15f8700du},  // Scenario Female
  {"Factory Worker Female", "s_f_y_factory_01", 9, 0x69f46bf3u},  // Scenario Female
  {"Hooker", "s_f_y_hooker_01", 9, 0x028abf95u},  // Scenario Female
  {"Hooker 2", "s_f_y_hooker_02", 9, 0x14c3e407u},  // Scenario Female
  {"Hooker 3", "s_f_y_hooker_03", 9, 0x031640acu},  // Scenario Female
  {"Hospital Scrubs Female", "s_f_y_scrubs_01", 9, 0xab594ab6u},  // Scenario Female
  {"Maid", "s_f_m_maid_01", 9, 0xe093c5c6u},  // Scenario Female
  {"Migrant Female", "s_f_y_migrant_01", 9, 0xd55b2bf5u},  // Scenario Female
  {"Movie Premiere Female", "s_f_y_movprem_01", 9, 0x2300c816u},  // Scenario Female
  {"Park Ranger Female", "s_f_y_ranger_01", 9, 0x9fc7f637u},  // Scenario Female
  {"Retailstaff", "s_f_m_retailstaff_01", 9, 0xc19c2462u},  // Scenario Female
  {"Sales Assistant (High-End)", "s_f_m_shop_high", 9, 0xae47e4b0u},  // Scenario Female
  {"Sales Assistant (Low-End)", "s_f_y_shop_low", 9, 0xa96e2604u},  // Scenario Female
  {"Sales Assistant (Mid-Price)", "s_f_y_shop_mid", 9, 0x3eecba5du},  // Scenario Female
  {"Sheriff Female", "s_f_y_sheriff_01", 9, 0x4161d042u},  // Scenario Female
  {"Stripper", "s_f_y_stripper_01", 9, 0x52580019u},  // Scenario Female
  {"Stripper 2", "s_f_y_stripper_02", 9, 0x6e0fb794u},  // Scenario Female
  {"Stripper Lite", "s_f_y_stripperlite", 9, 0x5c14edfau},  // Scenario Female
  {"Studio Assistant", "s_f_m_studioassist_01", 9, 0xc155acc0u},  // Scenario Female
  {"Sweatshop Worker", "s_f_m_sweatshop_01", 9, 0x312b5bc0u},  // Scenario Female
  {"Sweatshop Worker Young", "s_f_y_sweatshop_01", 9, 0x8502b6b2u},  // Scenario Female
  {"Warehouse Employee Female", "s_f_m_warehouse_01", 9, 0xe5371b92u},  // Scenario Female
  {"Air Worker Male", "s_m_y_airworker", 10, 0x62018559u},  // Scenario Male
  {"Alien", "s_m_m_movalien_01", 10, 0x64611296u},  // Scenario Male
  {"Ammu-Nation City Clerk", "s_m_y_ammucity_01", 10, 0x9e08633du},  // Scenario Male
  {"Ammu-Nation Rural Clerk", "s_m_m_ammucountry", 10, 0x0de9a30au},  // Scenario Male
  {"Armoured Van Security", "s_m_m_armoured_01", 10, 0x95c76ecdu},  // Scenario Male
  {"Armoured Van Security 2", "s_m_m_armoured_02", 10, 0x63858a4au},  // Scenario Male
  {"Army Mechanic", "s_m_y_armymech_01", 10, 0x62cc28e2u},  // Scenario Male
  {"Autopsy Tech", "s_m_y_autopsy_01", 10, 0xb2273d4eu},  // Scenario Male
  {"Autoshop Worker", "s_m_m_autoshop_01", 10, 0x040eabe3u},  // Scenario Male
  {"Autoshop Worker 2", "s_m_m_autoshop_02", 10, 0xf06b849du},  // Scenario Male
  {"Autoshop Worker 3", "s_m_m_autoshop_03", 10, 0x068c3112u},  // Scenario Male
  {"Bail Office Worker", "s_m_m_bailoffice_01", 10, 0x0a5e0b3fu},  // Scenario Male
  {"Barman", "s_m_y_barman_01", 10, 0xe5a11106u},  // Scenario Male
  {"Bartender (Rural)", "s_m_m_cntrybar_01", 10, 0x1a021b83u},  // Scenario Male
  {"Baywatch Male", "s_m_y_baywatch_01", 10, 0x0b4a6862u},  // Scenario Male
  {"Black Ops Soldier", "s_m_y_blackops_01", 10, 0xb3f3ee34u},  // Scenario Male
  {"Black Ops Soldier 2", "s_m_y_blackops_02", 10, 0x7a05fa59u},  // Scenario Male
  {"Black Ops Soldier 3", "s_m_y_blackops_03", 10, 0x5076a73bu},  // Scenario Male
  {"Bouncer", "s_m_m_bouncer_01", 10, 0x9fd4292du},  // Scenario Male
  {"Bouncer 2", "s_m_m_bouncer_02", 10, 0x52060d92u},  // Scenario Male
  {"Busboy", "s_m_y_busboy_01", 10, 0xd8f9cd47u},  // Scenario Male
  {"Busker", "s_m_o_busker_01", 10, 0xad9ef1bbu},  // Scenario Male
  {"Casino Staff", "s_m_y_casino_01", 10, 0x1422d45bu},  // Scenario Male
  {"Chef", "s_m_y_chef_01", 10, 0x0f977cebu},  // Scenario Male
  {"Chemical Plant Security", "s_m_m_chemsec_01", 10, 0x2efeafd5u},  // Scenario Male
  {"Clown", "s_m_y_clown_01", 10, 0x04498ddeu},  // Scenario Male
  {"Club Bartender Male", "s_m_y_clubbar_01", 10, 0x4d73a43fu},  // Scenario Male
  {"construction Worker", "s_m_y_construct_01", 10, 0xd7da9e99u},  // Scenario Male
  {"construction Worker 2", "s_m_y_construct_02", 10, 0xc5fefadeu},  // Scenario Male
  {"Cop Male", "s_m_y_cop_01", 10, 0x5e3da4a4u},  // Scenario Male
  {"Cop Male 2", "s_m_m_cop_01", 10, 0x69117a0eu},  // Scenario Male
  {"Crew Member", "s_m_m_ccrew_01", 10, 0xc9e5f56bu},  // Scenario Male
  {"Crew Member 2", "s_m_m_ccrew_02", 10, 0xb7a250e4u},  // Scenario Male
  {"Crew Member 3", "s_m_m_ccrew_03", 10, 0xe681aea2u},  // Scenario Male
  {"Dealer", "s_m_y_dealer_01", 10, 0xe497bbefu},  // Scenario Male
  {"Devin's Security", "s_m_y_devinsec_01", 10, 0x9b557274u},  // Scenario Male
  {"Dock Worker", "s_m_m_dockwork_01", 10, 0x14d7b4e0u},  // Scenario Male
  {"Dock Worker", "s_m_y_dockwork_01", 10, 0x867639d1u},  // Scenario Male
  {"Doctor", "s_m_m_doctor_01", 10, 0xd47303acu},  // Scenario Male
  {"Doorman", "s_m_y_doorman_01", 10, 0x22911304u},  // Scenario Male
  {"Drug Processer", "s_m_m_drugprocess_01", 10, 0x5c366c83u},  // Scenario Male
  {"Duggan Secruity", "s_m_y_westsec_01", 10, 0xa217f345u},  // Scenario Male
  {"Duggan Security 2", "s_m_y_westsec_02", 10, 0xbec82ca5u},  // Scenario Male
  {"DW Airport Worker", "s_m_y_dwservice_01", 10, 0x75d30a91u},  // Scenario Male
  {"DW Airport Worker 2", "s_m_y_dwservice_02", 10, 0xf5908a06u},  // Scenario Male
  {"Factory Worker Male", "s_m_y_factory_01", 10, 0x4163a158u},  // Scenario Male
  {"FIB Office Worker", "s_m_m_fiboffice_01", 10, 0xedbc7546u},  // Scenario Male
  {"FIB Office Worker 2", "s_m_m_fiboffice_02", 10, 0x26f067adu},  // Scenario Male
  {"FIB Security", "s_m_m_fibsec_01", 10, 0x7b8b434bu},  // Scenario Male
  {"Field Worker", "s_m_m_fieldworker_01", 10, 0x9074ca50u},  // Scenario Male
  {"Fireman Male", "s_m_y_fireman_01", 10, 0xb6b1eda8u},  // Scenario Male
  {"Gaffer", "s_m_m_gaffer_01", 10, 0xa956bd9eu},  // Scenario Male
  {"Garbage Worker", "s_m_y_garbage", 10, 0xee75a00fu},  // Scenario Male
  {"Gardener", "s_m_m_gardener_01", 10, 0x49ea5685u},  // Scenario Male
  {"Grip", "s_m_y_grip_01", 10, 0x309e7deau},  // Scenario Male
  {"Hairdresser Male", "s_m_m_hairdress_01", 10, 0x418dff92u},  // Scenario Male
  {"Hazmat Worker Male", "s_m_m_hazmatworker_01", 10, 0xdbd333d9u},  // Scenario Male
  {"High Security", "s_m_m_highsec_01", 10, 0xf161d212u},  // Scenario Male
  {"High Security 2", "s_m_m_highsec_02", 10, 0x2930c1abu},  // Scenario Male
  {"High Security 3", "s_m_m_highsec_03", 10, 0x1eeaad1fu},  // Scenario Male
  {"High Security 4", "s_m_m_highsec_04", 10, 0x55fe9b46u},  // Scenario Male
  {"High Security 5", "s_m_m_highsec_05", 10, 0x3abb64c0u},  // Scenario Male
  {"High Security 6", "s_m_m_highsec_06", 10, 0x716a521du},  // Scenario Male
  {"Highway Cop", "s_m_y_hwaycop_01", 10, 0x739b1ef5u},  // Scenario Male
  {"IAA Security", "s_m_m_ciasec_01", 10, 0x625d6958u},  // Scenario Male
  {"Janitor", "s_m_m_janitor", 10, 0xa96bd9ecu},  // Scenario Male
  {"Latino Handyman Male", "s_m_m_lathandy_01", 10, 0x9e80d2ceu},  // Scenario Male
  {"Life Invader Male", "s_m_m_lifeinvad_01", 10, 0xde0077fdu},  // Scenario Male
  {"Line Cook", "s_m_m_linecook", 10, 0xdb9c0997u},  // Scenario Male
  {"LS Metro Worker Male", "s_m_m_lsmetro_01", 10, 0x765aaae4u},  // Scenario Male
  {"Mariachi", "s_m_m_mariachi_01", 10, 0x7ea4ffa6u},  // Scenario Male
  {"Marine", "s_m_m_marine_01", 10, 0xf2daa2edu},  // Scenario Male
  {"Marine 2", "s_m_m_marine_02", 10, 0xf0259d83u},  // Scenario Male
  {"Marine Young", "s_m_y_marine_01", 10, 0x65793043u},  // Scenario Male
  {"Marine Young 2", "s_m_y_marine_02", 10, 0x58d696feu},  // Scenario Male
  {"Marine Young 3", "s_m_y_marine_03", 10, 0x72c0cad2u},  // Scenario Male
  {"Mask Salesman", "s_m_y_shop_mask", 10, 0x6e122c06u},  // Scenario Male
  {"MC Clubhouse Mechanic", "s_m_y_xmech_02", 10, 0xbe20fa04u},  // Scenario Male
  {"MC Clubhouse Mechanic 2?", "s_m_y_xmech_02_mp", 10, 0x69147a0du},  // Scenario Male
  {"Mechanic", "s_m_y_xmech_01", 10, 0x441405ecu},  // Scenario Male
  {"Migrant Male", "s_m_m_migrant_01", 10, 0xed0ce4c6u},  // Scenario Male
  {"Mime Artist", "s_m_y_mime", 10, 0x3cdca742u},  // Scenario Male
  {"Movie Astronaut", "s_m_m_movspace_01", 10, 0xe7b31432u},  // Scenario Male
  {"Movie Premiere Male", "s_m_m_movprem_01", 10, 0xd85e6d28u},  // Scenario Male
  {"Paramedic", "s_m_m_paramedic_01", 10, 0xb353629eu},  // Scenario Male
  {"Pest Control", "s_m_y_pestcont_01", 10, 0x48114518u},  // Scenario Male
  {"Pilot", "s_m_m_pilot_01", 10, 0xe75b4b1cu},  // Scenario Male
  {"Pilot", "s_m_y_pilot_01", 10, 0xab300c07u},  // Scenario Male
  {"Pilot 2", "s_m_m_pilot_02", 10, 0xf63de8e1u},  // Scenario Male
  {"Postal Worker Male", "s_m_m_postal_01", 10, 0x62599034u},  // Scenario Male
  {"Postal Worker Male 2", "s_m_m_postal_02", 10, 0x7367324fu},  // Scenario Male
  {"Prison Guard", "s_m_m_prisguard_01", 10, 0x56c96fc6u},  // Scenario Male
  {"Prisoner", "s_m_y_prisoner_01", 10, 0xb1bb9b59u},  // Scenario Male
  {"Prisoner (Muscular)", "s_m_y_prismuscl_01", 10, 0x5f2113a1u},  // Scenario Male
  {"Racer Organisator", "s_m_m_raceorg_01", 10, 0x9ad98d99u},  // Scenario Male
  {"Ranger Male", "s_m_y_ranger_01", 10, 0xef7135aeu},  // Scenario Male
  {"Robber", "s_m_y_robber_01", 10, 0xc05e1399u},  // Scenario Male
  {"Scientist", "s_m_m_scientist_01", 10, 0x4117d39bu},  // Scenario Male
  {"Security Guard", "s_m_m_security_01", 10, 0xd768b228u},  // Scenario Male
  {"Sheriff Male", "s_m_y_sheriff_01", 10, 0xb144f9b9u},  // Scenario Male
  {"Snow Cop Male", "s_m_m_snowcop_01", 10, 0x1ae8bb58u},  // Scenario Male
  {"Street Performer", "s_m_m_strperf_01", 10, 0x795ac7a8u},  // Scenario Male
  {"Street Preacher", "s_m_m_strpreach_01", 10, 0x1c0077fbu},  // Scenario Male
  {"Street Vendor", "s_m_m_strvend_01", 10, 0xce9113a9u},  // Scenario Male
  {"Street Vendor Young", "s_m_y_strvend_01", 10, 0x927f2323u},  // Scenario Male
  {"Studio Assistant Male", "s_m_m_studioassist_02", 10, 0x9fb16928u},  // Scenario Male
  {"Studio Producer Male", "s_m_m_studioprod_01", 10, 0xe3a30bbfu},  // Scenario Male
  {"Studio Sound Engineer Male", "s_m_m_studiosoueng_02", 10, 0xde08c410u},  // Scenario Male
  {"Sub Crew Male", "s_m_m_subcrew_01", 10, 0xded5e96bu},  // Scenario Male
  {"SWAT", "s_m_y_swat_01", 10, 0x8d8f1b10u},  // Scenario Male
  {"Tattoo Artist 2", "s_m_m_tattoo_01", 10, 0xc41743ebu},  // Scenario Male
  {"Transport Worker Male", "s_m_m_gentransport", 10, 0x1880ed06u},  // Scenario Male
  {"Trucker Male", "s_m_m_trucker_01", 10, 0x59511a6cu},  // Scenario Male
  {"UPS Driver", "s_m_m_ups_01", 10, 0x9fc37f22u},  // Scenario Male
  {"UPS Driver 2", "s_m_m_ups_02", 10, 0xd0bde116u},  // Scenario Male
  {"US Coastguard", "s_m_y_uscg_01", 10, 0xca0050e9u},  // Scenario Male
  {"Valet", "s_m_y_valet_01", 10, 0x3b96f23eu},  // Scenario Male
  {"Waiter", "s_m_y_waiter_01", 10, 0xad4c724cu},  // Scenario Male
  {"Warehouse Employee Male", "s_m_m_warehouse_01", 10, 0x27589791u},  // Scenario Male
  {"Warehouse Technician", "s_m_y_waretech_01", 10, 0x48c7a430u},  // Scenario Male
  {"Window Cleaner", "s_m_y_winclean_01", 10, 0x550d8d9du},  // Scenario Male
  {"Beth", "u_f_y_beth", 11, 0x953f798bu},  // Story Scenario Female
  {"Biker Chic Female", "u_f_y_bikerchic", 11, 0xfa389d4fu},  // Story Scenario Female
  {"Carol", "u_f_o_carol", 11, 0x54597b3au},  // Story Scenario Female
  {"Casino Cashier", "u_f_m_casinocash_01", 11, 0xbb0d72f5u},  // Story Scenario Female
  {"Casino shop owner", "u_f_m_casinoshop_01", 11, 0x1427d428u},  // Story Scenario Female
  {"Corpse Female", "u_f_m_corpse_01", 11, 0x2e140314u},  // Story Scenario Female
  {"Corpse Young Female", "u_f_y_corpse_01", 11, 0x9c70109du},  // Story Scenario Female
  {"Corpse Young Female 2", "u_f_y_corpse_02", 11, 0x0d9c72f8u},  // Story Scenario Female
  {"Debbie (Agatha's Secretary)", "u_f_m_debbie_01", 11, 0x0d575a46u},  // Story Scenario Female
  {"Drowned Victim Female", "u_f_m_drowned_01", 11, 0xd7f37609u},  // Story Scenario Female
  {"Eileen", "u_f_o_eileen", 11, 0x9ccd13f8u},  // Story Scenario Female
  {"Female Club Dancer (Burlesque)", "u_f_y_danceburl_01", 11, 0x0d4546aau},  // Story Scenario Female
  {"Female Club Dancer (Leather)", "u_f_y_dancelthr_01", 11, 0x07c8a6bbu},  // Story Scenario Female
  {"Female Club Dancer (Rave)", "u_f_y_dancerave_01", 11, 0xace2a1f1u},  // Story Scenario Female
  {"Hot Posh Female", "u_f_y_hotposh_01", 11, 0x969b6dfeu},  // Story Scenario Female
  {"Jane", "u_f_y_comjane", 11, 0xb6aa85ceu},  // Story Scenario Female
  {"Jeweller Assistant", "u_f_y_jewelass_01", 11, 0xf0d4be2eu},  // Story Scenario Female
  {"Lauren", "u_f_y_lauren", 11, 0x39ac5284u},  // Story Scenario Female
  {"Miranda", "u_f_m_miranda", 11, 0x414fa27bu},  // Story Scenario Female
  {"Miranda 2", "u_f_m_miranda_02", 11, 0xebbb0cb4u},  // Story Scenario Female
  {"Mistress", "u_f_y_mistress", 11, 0x5dca2528u},  // Story Scenario Female
  {"Movie Star Female", "u_f_o_moviestar", 11, 0x35578634u},  // Story Scenario Female
  {"Poppy Mitchell", "u_f_y_poppymich", 11, 0x23e9a09eu},  // Story Scenario Female
  {"Poppy Mitchell 2", "u_f_y_poppymich_02", 11, 0x6cb605fbu},  // Story Scenario Female
  {"Princess", "u_f_y_princess", 11, 0xd2e3a284u},  // Story Scenario Female
  {"Prologue Host Old Female", "u_f_o_prolhost_01", 11, 0xc512dd23u},  // Story Scenario Female
  {"Prologue Mourner Female", "u_f_m_promourn_01", 11, 0xa20899e7u},  // Story Scenario Female
  {"Spy Actress", "u_f_y_spyactress", 11, 0x5b81d86cu},  // Story Scenario Female
  {"Taylor", "u_f_y_taylor", 11, 0x1ad698a0u},  // Story Scenario Female
  {"Abner", "u_m_y_abner", 12, 0xf0ac2626u},  // Story Scenario Male
  {"Al Di Napoli Male", "u_m_m_aldinapoli", 12, 0xf0ec56e2u},  // Story Scenario Male
  {"Anton Beaudelaire", "u_m_y_antonb", 12, 0xcf623a2cu},  // Story Scenario Male
  {"Avon Juggernaut", "u_m_y_juggernaut_01", 12, 0x90ef5134u},  // Story Scenario Male
  {"Avon Juggernaut 2", "u_m_y_juggernaut_02", 12, 0xa340f5d7u},  // Story Scenario Male
  {"Avon Juggernaut 3", "u_m_m_juggernaut_03", 12, 0x9fcb2a9au},  // Story Scenario Male
  {"Baby D", "u_m_y_babyd", 12, 0xda116e7eu},  // Story Scenario Male
  {"Bank Manager Male", "u_m_m_bankman", 12, 0xc306d6f5u},  // Story Scenario Male
  {"Bike Hire Guy", "u_m_m_bikehire_01", 12, 0x76474545u},  // Story Scenario Male
  {"Blane", "u_m_m_blane", 12, 0x97989c98u},  // Story Scenario Male
  {"Burger Drug Worker", "u_m_y_burgerdrug_01", 12, 0x8b7d3766u},  // Story Scenario Male
  {"Caleb", "u_m_y_caleb", 12, 0xf760d12cu},  // Story Scenario Male
  {"Casino Thief", "u_m_y_croupthief_01", 12, 0x7fe3dec7u},  // Story Scenario Male
  {"Chip", "u_m_y_chip", 12, 0x24604b2bu},  // Story Scenario Male
  {"Curtis", "u_m_m_curtis", 12, 0xf8056a75u},  // Story Scenario Male
  {"Cyclist Male", "u_m_y_cyclist_01", 12, 0x2d0efcebu},  // Story Scenario Male
  {"Dead Courier", "u_m_y_corpse_01", 12, 0x94c2a03fu},  // Story Scenario Male
  {"Dean", "u_m_o_dean", 12, 0xf9ab1c8bu},  // Story Scenario Male
  {"DOA Male", "u_m_m_doa_01", 12, 0x621e6bfdu},  // Story Scenario Male
  {"Ed Toh", "u_m_m_edtoh", 12, 0x2a797197u},  // Story Scenario Male
  {"Ex-Mil Bum", "u_m_y_militarybum", 12, 0x4705974au},  // Story Scenario Male
  {"FIB Architect", "u_m_m_fibarchitect", 12, 0x342333d3u},  // Story Scenario Male
  {"FIB Mugger", "u_m_y_fibmugger_01", 12, 0x85b9c668u},  // Story Scenario Male
  {"Financial Guru", "u_m_o_finguru_01", 12, 0x46e39e63u},  // Story Scenario Male
  {"Gabriel", "u_m_y_gabriel", 12, 0x4c31c4a1u},  // Story Scenario Male
  {"Glen-Stank Male", "u_m_m_glenstank_01", 12, 0x45bb1666u},  // Story Scenario Male
  {"Griff", "u_m_m_griff_01", 12, 0xc454bcbbu},  // Story Scenario Male
  {"Guido", "u_m_y_guido_01", 12, 0xc6b49a2fu},  // Story Scenario Male
  {"Gun Vendor", "u_m_y_gunvend_01", 12, 0xb3229752u},  // Story Scenario Male
  {"Hangar Mechanic", "u_m_y_smugmech_01", 12, 0xcd6741a5u},  // Story Scenario Male
  {"Hippie Male", "u_m_y_hippie_01", 12, 0xf041880bu},  // Story Scenario Male
  {"Impotent Rage", "u_m_y_imporage", 12, 0x348065f5u},  // Story Scenario Male
  {"Jesco White (Tapdancing Hillbilly)", "u_m_o_taphillbilly", 12, 0x9a1e5e52u},  // Story Scenario Male
  {"Jesus", "u_m_m_jesus_01", 12, 0xce2cb751u},  // Story Scenario Male
  {"Jewel Thief", "u_m_m_jewelthief", 12, 0xe6cc3cdcu},  // Story Scenario Male
  {"Jeweller Security", "u_m_m_jewelsec_01", 12, 0xacccbdb6u},  // Story Scenario Male
  {"Justin Sex Tape Male", "u_m_y_justin", 12, 0x7dc3908fu},  // Story Scenario Male
  {"Kifflom Guy", "u_m_y_baygor", 12, 0x5244247du},  // Story Scenario Male
  {"Love Fist Willy", "u_m_m_willyfist", 12, 0x90769a8fu},  // Story Scenario Male
  {"Male Club Dancer (Burlesque)", "u_m_y_danceburl_01", 12, 0x56034ef2u},  // Story Scenario Male
  {"Male Club Dancer (Leather)", "u_m_y_dancelthr_01", 12, 0xfa7b4566u},  // Story Scenario Male
  {"Male Club Dancer (Rave)", "u_m_y_dancerave_01", 12, 0x7fe3dd1fu},  // Story Scenario Male
  {"Mani", "u_m_y_mani", 12, 0xc8bb1e52u},  // Story Scenario Male
  {"Mark Fostenburg", "u_m_m_markfost", 12, 0x1c95cb0bu},  // Story Scenario Male
  {"Movie Corpse (Suited)", "u_m_o_filmnoir", 12, 0x2bacc2dbu},  // Story Scenario Male
  {"Movie Director", "u_m_m_filmdirector", 12, 0x2b6e1bb6u},  // Story Scenario Male
  {"Paparazzi Young Male", "u_m_y_paparazzi", 12, 0x5048b328u},  // Story Scenario Male
  {"Party Target", "u_m_m_partytarget", 12, 0x81f74de7u},  // Story Scenario Male
  {"Partygoer Male", "u_m_y_party_01", 12, 0x36e70600u},  // Story Scenario Male
  {"Pogo the Monkey", "u_m_y_pogo_01", 12, 0xdc59940du},  // Story Scenario Male
  {"Prisoner", "u_m_y_prisoner_01", 12, 0x7b9b4bc0u},  // Story Scenario Male
  {"Prologue Driver", "u_m_y_proldriver_01", 12, 0x855e36a3u},  // Story Scenario Male
  {"Prologue Mourner Male", "u_m_m_promourn_01", 12, 0xce96030bu},  // Story Scenario Male
  {"Prologue Security", "u_m_m_prolsec_01", 12, 0x709220c7u},  // Story Scenario Male
  {"Republican Space Ranger", "u_m_y_rsranger_01", 12, 0x3c438cd2u},  // Story Scenario Male
  {"Rival Paparazzo", "u_m_m_rivalpap", 12, 0x60d5d6dau},  // Story Scenario Male
  {"Sports Biker", "u_m_y_sbike", 12, 0x6af4185du},  // Story Scenario Male
  {"Spy Actor", "u_m_m_spyactor", 12, 0xac0ea5d8u},  // Story Scenario Male
  {"Stag Party Groom", "u_m_y_staggrm_01", 12, 0x9194ce03u},  // Story Scenario Male
  {"Street Art Male", "u_m_m_streetart_01", 12, 0x6c19e962u},  // Story Scenario Male
  {"Tattoo Artist", "u_m_y_tattoo_01", 12, 0x94ae2b8cu},  // Story Scenario Male
  {"The Gooch (Grinch Parody)", "u_m_m_yulemonster", 12, 0xd32eefadu},  // Story Scenario Male
  {"Tramp Old Male", "u_m_o_tramp_01", 12, 0x6a8f1f9bu},  // Story Scenario Male
  {"Ushi", "u_m_y_ushi", 12, 0xfb6c0b97u},  // Story Scenario Male
  {"Vince", "u_m_m_vince", 12, 0x969e7c76u},  // Story Scenario Male
  {"Yeti (White Bigfoot / Sassquash)", "u_m_m_yeti", 12, 0x8ce6a476u},  // Story Scenario Male
  {"Zombie", "u_m_y_zombie_01", 12, 0xac4b4506u},  // Story Scenario Male
  {"Jewel Heist Driver", "hc_driver", 13, 0x3b474adfu},  // Others
  {"Jewel Heist Gunman", "hc_gunman", 13, 0x0b881aeeu},  // Others
  {"Jewel Heist Hacker", "hc_hacker", 13, 0x99bb00f8u},  // Others
  {"Zombie 1", "g_m_m_zombie_01", 13, 0xc61b7851u},  // Others
  {"Zombie 2", "g_m_m_zombie_02", 13, 0x98549cc4u},  // Others
  {"Zombie 3", "g_m_m_zombie_03", 13, 0x179d1b4fu},  // Others
  {"Zombie 4", "g_m_m_zombie_04", 13, 0x296ebef2u},  // Others
  {"Zombie 5", "g_m_m_zombie_05", 13, 0xfab86186u},  // Others
