// AUTO-GENERATED by devtools/generators/generate_scenario_registry.py
// Source: data/scenarios/gtav-scenario-names.txt
// Do not edit by hand. Regenerate with `make scenario-registry`.
//
// Initializer list for gtav_scenario_catalog[] (see feature_catalog.c).
// Columns: {label, scenario name, category index}.
// 89 entries across 7 categories.

  {"Atm", "PROP_HUMAN_ATM", 0},  // Standing / Idle
  {"Binoculars", "WORLD_HUMAN_BINOCULARS", 0},  // Standing / Idle
  {"Bum Bin", "PROP_HUMAN_BUM_BIN", 0},  // Standing / Idle
  {"Cheering", "WORLD_HUMAN_CHEERING", 0},  // Standing / Idle
  {"Guard Patrol", "WORLD_HUMAN_GUARD_PATROL", 0},  // Standing / Idle
  {"Hanging Out (Street)", "WORLD_HUMAN_HANG_OUT_STREET", 0},  // Standing / Idle
  {"Hobo Stand", "WORLD_HUMAN_BUM_STANDING", 0},  // Standing / Idle
  {"Holding Sign", "WORLD_HUMAN_BUM_FREEWAY", 0},  // Standing / Idle
  {"Human Statue", "WORLD_HUMAN_HUMAN_STATUE", 0},  // Standing / Idle
  {"Jog Standing", "WORLD_HUMAN_JOG_STANDING", 0},  // Standing / Idle
  {"Laying Down (Hobo)", "WORLD_HUMAN_BUM_SLUMPED", 0},  // Standing / Idle
  {"Movie Bulb", "PROP_HUMAN_MOVIE_BULB", 0},  // Standing / Idle
  {"Parking Meter", "PROP_HUMAN_PARKING_METER", 0},  // Standing / Idle
  {"Partying", "WORLD_HUMAN_PARTYING", 0},  // Standing / Idle
  {"Shocked", "WORLD_HUMAN_MOBILE_FILM_SHOCKING", 0},  // Standing / Idle
  {"Soldier Stand", "WORLD_HUMAN_GUARD_STAND_ARMY", 0},  // Standing / Idle
  {"Stand Fire", "WORLD_HUMAN_STAND_FIRE", 0},  // Standing / Idle
  {"Stand Impatient", "PROP_HUMAN_STAND_IMPATIENT", 0},  // Standing / Idle
  {"Standing Guard", "WORLD_HUMAN_GUARD_STAND", 0},  // Standing / Idle
  {"Standing Impatiently", "WORLD_HUMAN_STAND_IMPATIENT", 0},  // Standing / Idle
  {"Standing Impatiently 2", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT", 0},  // Standing / Idle
  {"Standing With Phone", "WORLD_HUMAN_STAND_MOBILE", 0},  // Standing / Idle
  {"Standing With Phone 2", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT", 0},  // Standing / Idle
  {"Superhero", "WORLD_HUMAN_SUPERHERO", 0},  // Standing / Idle
  {"Tourist Map", "WORLD_HUMAN_TOURIST_MAP", 0},  // Standing / Idle
  {"Tourist Mobile", "WORLD_HUMAN_TOURIST_MOBILE", 0},  // Standing / Idle
  {"Leaning", "WORLD_HUMAN_LEANING", 1},  // Leaning
  {"Drinking", "WORLD_HUMAN_DRINKING", 2},  // Smoking & Drinking
  {"Drinking Coffee", "WORLD_HUMAN_AA_COFFEE", 2},  // Smoking & Drinking
  {"Drunk", "WORLD_HUMAN_STUPOR", 2},  // Smoking & Drinking
  {"Smoking", "WORLD_HUMAN_SMOKING", 2},  // Smoking & Drinking
  {"Smoking 2", "WORLD_HUMAN_AA_SMOKE", 2},  // Smoking & Drinking
  {"Smoking Weed", "WORLD_HUMAN_SMOKING_POT", 2},  // Smoking & Drinking
  {"BBQ", "PROP_HUMAN_BBQ", 3},  // Seated / Props
  {"Picnic", "WORLD_HUMAN_PICNIC", 3},  // Seated / Props
  {"Seat Armchair", "PROP_HUMAN_SEAT_ARMCHAIR", 3},  // Seated / Props
  {"Seat Bar", "PROP_HUMAN_SEAT_BAR", 3},  // Seated / Props
  {"Seat Bench", "PROP_HUMAN_SEAT_BENCH", 3},  // Seated / Props
  {"Seat Chair", "PROP_HUMAN_SEAT_CHAIR", 3},  // Seated / Props
  {"Seat Computer", "PROP_HUMAN_SEAT_COMPUTER", 3},  // Seated / Props
  {"Seat Deckchair", "PROP_HUMAN_SEAT_DECKCHAIR", 3},  // Seated / Props
  {"Seat Ledge", "WORLD_HUMAN_SEAT_LEDGE", 3},  // Seated / Props
  {"Seat Sewing", "PROP_HUMAN_SEAT_SEWING", 3},  // Seated / Props
  {"Seat Steps", "WORLD_HUMAN_SEAT_STEPS", 3},  // Seated / Props
  {"Seat Sunlounger", "PROP_HUMAN_SEAT_SUNLOUNGER", 3},  // Seated / Props
  {"Seat Train", "PROP_HUMAN_SEAT_TRAIN", 3},  // Seated / Props
  {"Seat Wall", "WORLD_HUMAN_SEAT_WALL", 3},  // Seated / Props
  {"Sunbathing", "WORLD_HUMAN_SUNBATHE", 3},  // Seated / Props
  {"Sunbathing 2", "WORLD_HUMAN_SUNBATHE_BACK", 3},  // Seated / Props
  {"Cleaning", "WORLD_HUMAN_MAID_CLEAN", 4},  // Work & Activities
  {"Clipboard", "WORLD_HUMAN_CLIPBOARD", 4},  // Work & Activities
  {"Drilling", "WORLD_HUMAN_CONST_DRILL", 4},  // Work & Activities
  {"Drug Dealer", "WORLD_HUMAN_DRUG_DEALER", 4},  // Work & Activities
  {"Drug Dealing", "WORLD_HUMAN_DRUG_DEALER_HARD", 4},  // Work & Activities
  {"Fishing", "WORLD_HUMAN_STAND_FISHING", 4},  // Work & Activities
  {"Gardening", "WORLD_HUMAN_GARDENER_PLANT", 4},  // Work & Activities
  {"Golf Player", "WORLD_HUMAN_GOLF_PLAYER", 4},  // Work & Activities
  {"Hammering", "WORLD_HUMAN_HAMMERING", 4},  // Work & Activities
  {"Hooker", "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", 4},  // Work & Activities
  {"Hooker 2", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", 4},  // Work & Activities
  {"Janitor", "WORLD_HUMAN_JANITOR", 4},  // Work & Activities
  {"Mechanic", "WORLD_HUMAN_VEHICLE_MECHANIC", 4},  // Work & Activities
  {"Musician", "WORLD_HUMAN_MUSICIAN", 4},  // Work & Activities
  {"Parking Attendant", "WORLD_HUMAN_CAR_PARK_ATTENDANT", 4},  // Work & Activities
  {"Play Bongos", "WORLD_HUMAN_MUSICIAN_MALE_BONGOS", 4},  // Work & Activities
  {"Play Guitar", "WORLD_HUMAN_MUSICIAN_MALE_GUITAR", 4},  // Work & Activities
  {"Shining Torch", "WORLD_HUMAN_SECURITY_SHINE_TORCH", 4},  // Work & Activities
  {"Taking Pictures", "WORLD_HUMAN_PAPARAZZI", 4},  // Work & Activities
  {"Tennis Player", "WORLD_HUMAN_TENNIS_PLAYER", 4},  // Work & Activities
  {"Wash", "WORLD_HUMAN_BUM_WASH", 4},  // Work & Activities
  {"Welding", "WORLD_HUMAN_WELDING", 4},  // Work & Activities
  {"Window Shopping", "WORLD_HUMAN_WINDOW_SHOP_BROWSE", 4},  // Work & Activities
  {"Doing Pushups", "WORLD_HUMAN_PUSH_UPS", 5},  // Fitness
  {"Doing Yoga", "WORLD_HUMAN_YOGA", 5},  // Fitness
  {"Flexing", "WORLD_HUMAN_MUSCLE_FLEX", 5},  // Fitness
  {"Hiker", "WORLD_HUMAN_HIKER", 5},  // Fitness
  {"Hiker Standing", "WORLD_HUMAN_HIKER_STANDING", 5},  // Fitness
  {"Jog", "WORLD_HUMAN_JOG", 5},  // Fitness
  {"Lifting Weights", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", 5},  // Fitness
  {"Power Walker", "WORLD_HUMAN_POWER_WALKER", 5},  // Fitness
  {"Sit Ups", "WORLD_HUMAN_SIT_UPS", 5},  // Fitness
  {"Swimming", "WORLD_HUMAN_SWIMMING", 5},  // Fitness
  {"Cop Idles", "WORLD_HUMAN_COP_IDLES", 6},  // Cower / Cop / Medic
  {"Cower", "CODE_HUMAN_COWER", 6},  // Cower / Cop / Medic
  {"Cower Stand", "CODE_HUMAN_COWER_STAND", 6},  // Cower / Cop / Medic
  {"Medic", "CODE_HUMAN_MEDIC_KNEEL", 6},  // Cower / Cop / Medic
  {"Park Car", "CODE_HUMAN_PARK_CAR", 6},  // Cower / Cop / Medic
  {"Police Investigate", "CODE_HUMAN_POLICE_INVESTIGATE", 6},  // Cower / Cop / Medic
  {"Stand Cower", "CODE_HUMAN_STAND_COWER", 6},  // Cower / Cop / Medic
