// AUTO-GENERATED by devtools/generators/generate_scenario_registry.py
// Source: data/scenarios/gtav-scenario-names.txt
// Do not edit by hand. Regenerate with `make scenario-registry`.
//
// Scenario category display names, in catalog category-index order. native_bridge.cpp
// prepends "All" (index 0); a catalog entry with category index N maps here to N.
// 7 categories.

    "Standing / Idle",
    "Leaning",
    "Smoking & Drinking",
    "Seated / Props",
    "Work & Activities",
    "Fitness",
    "Cower / Cop / Medic",
