// AUTO-GENERATED by devtools/generators/generate_script_globals_header.py
// Source: data/script_globals/anchors.json
// Do not edit by hand. Regenerate with `make script-globals-header`.
//
// Version-specific script-VM anchors, reverse-engineered from the PS5
// eboot once per game build (NOT resolved by the native crossmap). These
// are absolute live virtual addresses (eboot at its fixed link base, no
// ASLR slide). Each guard lets a -D override win over the baked value.
// Build: GTA V Enhanced (PS5) PPSA04264 / 01.010.002
// Resolved 1/2 anchors. They are data only and
// enable nothing without GTAV_MENU_ENABLE_SCRIPT_GLOBALS.
#pragma once

// The build these addresses were RE'd against. A mismatch against the build
// being compiled is a hard error, not a fallback -- see script_globals.h.
#define GTAV_SCRIPT_GLOBALS_ANCHOR_TARGET_ID "ppsa04264-01.010.002"

// SCRIPT_TABLE: TODO -- not yet reverse-engineered.
#ifndef GTAV_SCRIPT_TABLE_ADDR
#define GTAV_SCRIPT_TABLE_ADDR 0ull
#endif

// GLOBALS_BASE: live-verified.
#ifndef GTAV_GLOBALS_BASE_ADDR
#define GTAV_GLOBALS_BASE_ADDR 0x6155e90ull
#endif

// GTAV_DESPAWN_GLOBAL_INDEX: baked DIRECT-write (4520961u).
#ifndef GTAV_DESPAWN_GLOBAL_INDEX
#define GTAV_DESPAWN_GLOBAL_INDEX 4520961u
#endif

// GTAV_PROLOGUE_GLOBAL_INDEX: 0 (unset).
#ifndef GTAV_PROLOGUE_GLOBAL_INDEX
#define GTAV_PROLOGUE_GLOBAL_INDEX 0u
#endif

// GTAV_PROLOGUE_GLOBAL_CANDIDATES: 0 flow-completion flag(s) the prologue
// sets on completion (diff-derived; data/script_globals/anchors.json). The armed
// worker stamps ALL of them -- the launch gate f_330[53] is one of the set.
#ifndef GTAV_PROLOGUE_GLOBAL_CANDIDATES
#define GTAV_PROLOGUE_GLOBAL_CANDIDATES { 0u }
#endif
#ifndef GTAV_PROLOGUE_GLOBAL_CANDIDATE_COUNT
#define GTAV_PROLOGUE_GLOBAL_CANDIDATE_COUNT 0u
#endif
