# Exact target feature profile selected by data/targets/$(GTAV_TARGET).json.
#
# Command-line assignments still take precedence, which lets the supported watch and OnionHEN
# deliveries add their small lifecycle-specific overrides without copying the common feature set.
ENABLE_PAD_INPUT = 1
PAD_HOOK = 0
FEATURE_MENU_ENABLE_NATIVE_FEATURES := $(GTAV_TARGET_NATIVE_FEATURES)
FEATURE_MENU_ENABLE_FRAME_HOOK = 1
FRAME_HOOK_EXTERNAL_INSTALL = 1
FRAME_HOOK_CAPTURE_CONTEXT = 1
FRAME_HOOK_REQUIRE_CONTEXT = 1
FEATURE_MENU_GATE_MAINTHREAD = 1
GTAV_MENU_ENABLE_WORKER_TEXT_OVERLAY := $(GTAV_TARGET_WORKER_TEXT)
GTAV_MENU_ENABLE_TOASTS := $(GTAV_TARGET_TOASTS)
GTAV_MENU_ENABLE_VEHICLE_PREVIEW := $(GTAV_TARGET_VEHICLE_PREVIEW)
GTAV_MENU_ENABLE_INSTRUCTIONAL_SCALEFORM := $(GTAV_TARGET_INSTRUCTIONAL_SCALEFORM)
GTAV_MENU_ENABLE_BUTTON_GLYPHS := $(GTAV_TARGET_BUTTON_GLYPHS)
GTAV_MENU_ENABLE_WORKER_KLOG = 1
GTAV_MENU_ENABLE_QUIT_GUARD = 1
GTAV_MENU_QUIT_GUARD_APPSTATE = 1
SCRIPT_GLOBALS := $(GTAV_TARGET_SCRIPT_GLOBALS)
WORKER_REQUIRE_CONTEXT = 0
FRAME_HOOK_SELF_START_WORKER := $(GTAV_TARGET_SELF_START)
RENDER_PHASE_INTERCEPT := $(GTAV_TARGET_PHASE_INTERCEPT)
GTAV_MENU_PHASE_DRAW_LIST := $(GTAV_TARGET_PHASE_DRAW_LIST)
# Runtime custom pack lane (worker device/stream lane requiring game-visible /data), on where the
# target manifest sets features.customPacks (the 01.010.002 executables). `?=` so both
# `make all CUSTOM_PACKS=0` and `CUSTOM_PACKS=0 make all` build the lane-off variant.
CUSTOM_PACKS ?= $(GTAV_TARGET_CUSTOM_PACKS)

PAYLOAD_LOADER_PROBE_NOSTOP := $(GTAV_TARGET_PROBE_NOSTOP)
PAYLOAD_LOADER_NOSTOP_IO := $(GTAV_TARGET_NOSTOP_IO)
PAYLOAD_LOADER_NOSTOP_STRICT := $(GTAV_TARGET_NOSTOP_STRICT)
PAYLOAD_LOADER_VERIFY_WRITES := $(GTAV_TARGET_VERIFY_WRITES)
PAYLOAD_LOADER_CAVE_BOOTSTRAP := $(GTAV_TARGET_CAVE_BOOTSTRAP)
PAYLOAD_LOADER_CAVE_INJECT := $(GTAV_TARGET_CAVE_INJECT)
PAYLOAD_LOADER_CLASSIC_INJECT := $(GTAV_TARGET_CLASSIC_INJECT)
PAYLOAD_LOADER_INJECT = 1
PAYLOAD_LOADER_INSTALL_BROKER = 1
PAYLOAD_LOADER_INSTALL_RENDER_PHASE := $(GTAV_TARGET_INSTALL_PHASE)
PAYLOAD_LOADER_INJECT_GUARD = 1
PAYLOAD_LOADER_VERIFY_VERSION = 1
