# Canonical production feature profile for PPSA04264 / 01.010.002.
#
# Command-line assignments still take precedence, which lets the supported watch and OnionHEN
# deliveries add their small lifecycle-specific overrides without copying the common feature set.
ifneq ($(GTAV_TARGET),ppsa04264-01.010.002)
$(error GTAV_BUILD_PROFILE=production supports only ppsa04264-01.010.002; use the archived 01.005 reproduction tag for the older target)
endif

ENABLE_PAD_INPUT = 1
PAD_HOOK = 0
FEATURE_MENU_ENABLE_NATIVE_FEATURES = 1
FEATURE_MENU_ENABLE_FRAME_HOOK = 1
FRAME_HOOK_EXTERNAL_INSTALL = 1
FRAME_HOOK_CAPTURE_CONTEXT = 1
FRAME_HOOK_REQUIRE_CONTEXT = 1
FEATURE_MENU_GATE_MAINTHREAD = 1
GTAV_MENU_ENABLE_WORKER_TEXT_OVERLAY = 1
GTAV_MENU_ENABLE_TOASTS = 1
GTAV_MENU_ENABLE_VEHICLE_PREVIEW = 1
GTAV_MENU_ENABLE_INSTRUCTIONAL_SCALEFORM = 1
GTAV_MENU_ENABLE_BUTTON_GLYPHS = 0
GTAV_MENU_ENABLE_WORKER_KLOG = 1
GTAV_MENU_ENABLE_QUIT_GUARD = 1
GTAV_MENU_QUIT_GUARD_APPSTATE = 1
SCRIPT_GLOBALS = 1
WORKER_REQUIRE_CONTEXT = 0
FRAME_HOOK_SELF_START_WORKER = 1
RENDER_PHASE_INTERCEPT = 1
GTAV_MENU_PHASE_DRAW_LIST = 1

PAYLOAD_LOADER_PROBE_NOSTOP = 1
PAYLOAD_LOADER_NOSTOP_IO = 1
PAYLOAD_LOADER_NOSTOP_STRICT = 1
PAYLOAD_LOADER_VERIFY_WRITES = 1
PAYLOAD_LOADER_CAVE_BOOTSTRAP = 1
PAYLOAD_LOADER_CAVE_INJECT = 1
PAYLOAD_LOADER_INJECT = 1
PAYLOAD_LOADER_INSTALL_BROKER = 1
PAYLOAD_LOADER_INSTALL_RENDER_PHASE = 1
PAYLOAD_LOADER_INJECT_GUARD = 1
PAYLOAD_LOADER_VERIFY_VERSION = 1
