#!/usr/bin/env python3
"""Build reviewed workers once, then embed their registry in universal deliveries."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from gtavmenu_tools.target_profile import load_manifest, sha256_file

try:
    from tools.generate_loader_profiles import ROOT, SUPPORTED_TARGETS, generate, write_changed
except ModuleNotFoundError:
    from generate_loader_profiles import ROOT, SUPPORTED_TARGETS, generate, write_changed

DELIVERIES = ("standalone", "onionhen", "etahen")
WATCH_SETTINGS = (
    "WORKER_REQUIRE_CONTEXT=1",
    "PAYLOAD_LOADER_WAIT_FOR_GAME=1",
    "PAYLOAD_LOADER_PERSISTENT=1",
    "PAYLOAD_LOADER_SP_READY=1",
    "PAYLOAD_LOADER_SP_READY_DEREF=1",
    "PAYLOAD_LOADER_SP_READY_MODE=1",
    "PAYLOAD_LOADER_SP_READY_CONFIRMATIONS=3",
    "PAYLOAD_LOADER_SP_READY_SIZE=8",
    "PAYLOAD_LOADER_SP_READY_MASK=0xffffffffffffffff",
    "PAYLOAD_LOADER_SP_READY_VALUE=0",
)


def make_environment() -> dict[str, str]:
    # Parent make's selected target or -j settings must not leak across worker builds.
    return {key: value for key, value in os.environ.items() if key not in {"MAKEFLAGS", "MFLAGS", "MAKEOVERRIDES"}}


def build_config(registry: dict, registry_path: Path, delivery: str) -> dict:
    worker_config = json.loads(Path(registry["supportedTargets"][0]["workerBuildConfig"]["path"]).read_text())
    return {
        "schemaVersion": 1,
        "target": "universal",
        "profile": "production",
        "delivery": delivery,
        "sourceCommit": registry["sourceCommit"],
        "universal": 1,
        "persistent": 1,
        "embed_worker": 1,
        "target_ptrace": 0,
        "target_elevation": 0,
        "loader_wait": 1,
        "loader_sp_ready": 1,
        "worker_context": 1,
        "verify_writes": 1,
        "native_pins": 1,
        "registrySha256": sha256_file(registry_path),
        "inventorySha256": registry["inventorySha256"],
        "compilerVersion": worker_config["compilerVersion"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", type=Path, default=ROOT / "build/ps5")
    parser.add_argument("--sdk", type=Path, required=True)
    parser.add_argument("--deliveries", nargs="+", choices=DELIVERIES, default=list(DELIVERIES))
    parser.add_argument("--package", action="store_true")
    parser.add_argument("--package-dir", type=Path, default=ROOT / "build/pkg/universal")
    parser.add_argument("--onion-version", default="1.03")
    parser.add_argument("--eta-version", default="1.00")
    args = parser.parse_args()
    build_dir = args.build_dir.resolve()
    output = build_dir / "universal/production"
    make_base = [
        "make",
        "-j1",
        f"PYTHON={sys.executable}",
        f"PS5_PAYLOAD_SDK={args.sdk.resolve()}",
        f"BUILD_DIR={build_dir}",
        "GTAV_BUILD_PROFILE=production",
        "PS5_LLVM_MAJOR=20",
        "GTAV_ALLOW_UNVALIDATED_TOOLCHAIN=0",
    ]
    environment = make_environment()
    try:
        for target in SUPPORTED_TARGETS:
            manifest, _profile = load_manifest(ROOT / "data/targets" / f"{target}.json")
            subprocess.run(
                [
                    *make_base,
                    f"GTAV_TARGET={target}",
                    "GTAV_DELIVERY=standalone",
                    *WATCH_SETTINGS,
                    f"PAYLOAD_LOADER_SP_READY_ADDR={manifest['loader']['playerPedAnchor']}",
                    f"PAYLOAD_LOADER_SP_READY_DEREF_OFFSET={manifest['loader']['playerPedOffset']}",
                    "feature-menu-frame-hook-playerped-build",
                ],
                cwd=ROOT,
                env=environment,
                check=True,
            )
        registry = generate(ROOT, build_dir, output)
        for delivery in args.deliveries:
            directory = output / delivery
            config = build_config(registry, output / "registry.json", delivery)
            write_changed(directory / "build-config.json", json.dumps(config, indent=2, sort_keys=True) + "\n")
            write_changed(
                directory / "universal_identity.h",
                "/* Generated by tools/build_universal.py. */\n#pragma once\n"
                'static const char gtav_universal_registry_identity[] = "GTAVMENU_UNIVERSAL_REGISTRY_SHA256:'
                + config["registrySha256"]
                + '";\nstatic const char gtav_universal_build_identity[] = "GTAVMENU_UNIVERSAL_BUILD_SHA256:'
                + sha256_file(directory / "build-config.json")
                + '";\nstatic const char gtav_universal_inventory_identity[] = "GTAVMENU_UNIVERSAL_INVENTORY_SHA256:'
                + config["inventorySha256"]
                + '";\n',
            )
            subprocess.run(
                [
                    *make_base,
                    f"GTAV_TARGET={SUPPORTED_TARGETS[1]}",
                    f"GTAV_DELIVERY={delivery}",
                    f"ONIONHEN_PLUGIN_VERSION={args.onion_version}",
                    f"ETAHEN_PLUGIN_VERSION={args.eta_version}",
                    f"ETAHEN_RUNTIME_VERSION={args.eta_version}",
                    "_universal-link",
                ],
                cwd=ROOT,
                env=environment,
                check=True,
            )
            if args.package:
                runtime, artifact, version = {
                    "standalone": ("gtav-menu-payload-loader.elf", "gtav-menu-payload-loader.elf", "1.00"),
                    "onionhen": ("gtav-menu-onion-daemon.elf", "GTAV00001.elf", args.onion_version),
                    "etahen": ("gtav-menu-etahen-runtime.elf", "GTAV00001.plugin", args.eta_version),
                }[delivery]
                subprocess.run(
                    [
                        sys.executable,
                        "tools/package_universal.py",
                        "--delivery",
                        delivery,
                        "--runtime",
                        str(directory / runtime),
                        "--artifact",
                        str(directory / artifact),
                        "--inventory",
                        str(output / "registry.json"),
                        "--build-config",
                        str(directory / "build-config.json"),
                        "--output",
                        str(args.package_dir / delivery),
                        "--version",
                        version,
                    ],
                    cwd=ROOT,
                    check=True,
                )
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError) as exc:
        print(f"build_universal: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
