#!/usr/bin/env python3
"""Validate JSON locale catalogs and emit relocation-free C initializers."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

KEY_RE = re.compile(r"^[a-z0-9]+(?:[._][a-z0-9]+)*$")
PRINTF_RE = re.compile(r"%(?:[-+ #0]*\d*(?:\.\d+)?(?:hh|h|ll|l|j|z|t|L)?[diuoxXfFeEgGaAcspn%])")
TOKEN_RE = re.compile(r"~[^~]+~")
MAX_KEY_BYTES = 64
MAX_TEXT_BYTES = 128


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def placeholders(value: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    return tuple(x for x in PRINTF_RE.findall(value) if x != "%%"), tuple(TOKEN_RE.findall(value))


def load_catalogs(directory: Path) -> list[dict]:
    catalogs = [json.loads(path.read_text(encoding="utf-8")) for path in sorted(directory.glob("*.json"))]
    if not catalogs:
        raise SystemExit(f"no locale catalogs in {directory}")
    ids: set[int] = set()
    codes: set[str] = set()
    for catalog in catalogs:
        if catalog.get("schema") != 1:
            raise SystemExit(f"{catalog.get('code', '?')}: unsupported schema")
        locale_id = catalog.get("id")
        code = catalog.get("code")
        name = catalog.get("name")
        strings = catalog.get("strings")
        if not isinstance(locale_id, int) or locale_id < 0 or locale_id in ids:
            raise SystemExit(f"invalid or duplicate locale id: {locale_id!r}")
        if not isinstance(code, str) or not code or code in codes or len(code.encode()) >= 12:
            raise SystemExit(f"invalid or duplicate locale code: {code!r}")
        if not isinstance(name, str) or not name or len(name.encode()) >= 32:
            raise SystemExit(f"{code}: invalid display name")
        if not isinstance(strings, dict):
            raise SystemExit(f"{code}: strings must be an object")
        ids.add(locale_id)
        codes.add(code)
        for key, text in strings.items():
            if not KEY_RE.fullmatch(key) or len(key.encode()) >= MAX_KEY_BYTES:
                raise SystemExit(f"{code}: invalid or oversized key {key!r}")
            if not isinstance(text, str) or "\0" in text or len(text.encode()) >= MAX_TEXT_BYTES:
                raise SystemExit(f"{code}:{key}: text exceeds {MAX_TEXT_BYTES - 1} UTF-8 bytes")
    english = next((item for item in catalogs if item["id"] == 0 and item["code"] == "en"), None)
    if english is None:
        raise SystemExit("English catalog must keep stable id 0 and code en")
    english_values = list(english["strings"].values())
    if len(english_values) != len(set(english_values)):
        raise SystemExit("English source texts must be unique for compatibility lookup")
    english_keys = set(english["strings"])
    for catalog in catalogs:
        if set(catalog["strings"]) != english_keys:
            missing = sorted(english_keys - set(catalog["strings"]))
            extra = sorted(set(catalog["strings"]) - english_keys)
            raise SystemExit(f"{catalog['code']}: key mismatch missing={missing} extra={extra}")
        for key, text in catalog["strings"].items():
            if placeholders(text) != placeholders(english["strings"][key]):
                raise SystemExit(f"{catalog['code']}:{key}: printf/control tokens differ from English")
    return sorted(catalogs, key=lambda item: item["id"])


def render(catalogs: list[dict]) -> str:
    meta = [f'  {{{c["id"]}u, {c_string(c["code"])}, {c_string(c["name"])}}},' for c in catalogs]
    blob = bytearray()
    offsets: dict[str, int] = {}

    def intern(value: str) -> int:
        if value in offsets:
            return offsets[value]
        offset = len(blob)
        blob.extend(value.encode("utf-8"))
        blob.append(0)
        offsets[value] = offset
        return offset

    entries: list[str] = []
    for catalog in catalogs:
        for key, value in sorted(catalog["strings"].items()):
            entries.append(f'  {{{catalog["id"]}u, {intern(key)}u, {intern(value)}u}},')
    english = next(catalog for catalog in catalogs if catalog["id"] == 0)
    reverse = [
        f"  {{{intern(value)}u, {intern(key)}u}},"
        for key, value in sorted(english["strings"].items(), key=lambda item: item[1])
    ]
    blob_lines = []
    for value, offset in sorted(offsets.items(), key=lambda item: item[1]):
        del offset
        encoded = c_string(value)
        blob_lines.append(f'  {encoded[:-1]}\\0"')
    digest = hashlib.sha256(blob).hexdigest()
    return "\n".join(
        [
            "/* Generated by tools/generate_locales.py; do not edit. */",
            "#pragma once",
            "",
            f"#define GTAV_LOCALE_GENERATED_META_COUNT {len(meta)}u",
            f"#define GTAV_LOCALE_GENERATED_TEXT_COUNT {len(entries)}u",
            f"#define GTAV_LOCALE_GENERATED_REVERSE_COUNT {len(reverse)}u",
            f"#define GTAV_LOCALE_GENERATED_BLOB_SIZE {len(blob)}u",
            f'#define GTAV_LOCALE_GENERATED_BLOB_SHA256 "{digest}"',
            "#define GTAV_LOCALE_GENERATED_META \\",
            " \\\n".join(meta),
            "#define GTAV_LOCALE_GENERATED_TEXT \\",
            " \\\n".join(entries),
            "#define GTAV_LOCALE_GENERATED_REVERSE \\",
            " \\\n".join(reverse),
            "#define GTAV_LOCALE_GENERATED_BLOB \\",
            " \\\n".join(blob_lines),
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, default=Path("data/locales"))
    parser.add_argument("--output", type=Path, default=Path("include/gtavmenu/localization_generated.h"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render(load_catalogs(args.input_dir))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != output:
            raise SystemExit(f"stale generated locale header: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
