#!/usr/bin/env python3
"""Generate loader-only Git version metadata without rewriting unchanged headers."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def git_output(root: Path, *arguments: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *arguments],
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="surrogateescape",
        )
    except FileNotFoundError:
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def build_version(root: Path) -> str:
    top = git_output(root, "rev-parse", "--show-toplevel")
    # An unpacked source archive inside another checkout does not inherit that
    # unrelated repository's release identity.
    if top is None or Path(top).resolve() != root.resolve():
        return "dev"
    commit = git_output(root, "rev-parse", "--short=8", "HEAD")
    if commit is None:
        return "dev"
    status = git_output(root, "status", "--porcelain", "--untracked-files=no", "--ignore-submodules=none")
    if status is None:
        raise RuntimeError("cannot determine tracked Git changes for build version")
    if status:
        return commit + "-dirty"
    tags = git_output(root, "tag", "--points-at", "HEAD", "--list", "v*", "--sort=-version:refname")
    if tags is None:
        raise RuntimeError("cannot determine exact release tags for build version")
    return tags.splitlines()[0] if tags else commit


def c_string(value: str) -> str:
    # Emit UTF-8 as bounded octal escapes where needed. Unlike shell defines or
    # JSON's surrogate escapes, every possible Git ref byte remains valid C.
    escaped = []
    for byte in value.encode("utf-8", errors="surrogateescape"):
        if byte in (ord('"'), ord("\\")):
            escaped.append("\\" + chr(byte))
        elif 32 <= byte <= 126 and byte != ord("?"):
            escaped.append(chr(byte))
        else:
            escaped.append(f"\\{byte:03o}")
    return '"' + "".join(escaped) + '"'


def write_header(output: Path, version: str) -> bool:
    rendered = (
        "/* Generated by tools/write_build_version.py; loader only. */\n"
        "#pragma once\n"
        f"#define GTAV_MENU_BUILD_VERSION {c_string(version)}\n"
    )
    if output.is_file() and output.read_text(encoding="utf-8") == rendered:
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.{os.getpid()}.tmp")
    temporary.write_text(rendered, encoding="utf-8")
    temporary.replace(output)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    try:
        write_header(args.output, build_version(args.root))
    except (OSError, RuntimeError) as exc:
        print(f"build version failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
